version: "3.8"

networks:
  quickbite-network:
    driver: 
      bridge

services:
  sqldata:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - quickbite-network

  quickbite:
    container_name: app
    image: rickalbbraga/quickbite:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    ports:
      - "80:80"
    networks:
      - quickbite-network
    depends_on:
      - sqldata
      - queue
  
  rabbitmq:
    container_name: queue
    image: rabbitmq:3.9.29-management
    ports:
      - 5673:5672
      - 15673:15672
    networks:
      - quickbite-network
    