@startuml DomainStory-ProductManagement
title Product Management - General Overview for Product Registration

!include https://raw.githubusercontent.com/johthor/DomainStory-PlantUML/main/domainStory.puml
!include ProductActors.puml
!include ProductObjects.puml

Person(nutri, "Nutricionista")
Person(admin, "Administrador")
Person(customer, "cliente")


activity(_,nutri, lista , Recipes: Ingredientes das Receitas ,informa,  admin)
activity(_,nutri, cria ou altera, Recipes: Receita de Lanche, informa , admin)
activity(_,nutri, cria ou altera, Recipes: Receita de Acompanhamentos, informa , admin)
activity(_,nutri, cria ou altera, Recipes: Receita de Sobremesas, informa , admin)
activity(_,nutri, lista, Recipes: Catalogo ou Receitas de Bebidas, informa , admin)
activity(_,nutri, lista, Recipes: Catalogo de Produtos Unicos, informa , admin, $note= "Produtos como Molhos de Salada, Molho Barbecue, etc")




Boundary("productManager","Gestão de Produtos") {    
    System(sistema, "Gestão de Produtos")
    activity(_,admin, Inclui ou Altera, Info: Categorias,  no, sistema)    
    activity(_,admin, Inclui ou Altera, Ingredients: Ingredientes, no , sistema)
    activity(_,admin, Inclui ou Altera, Snacks: Lanches, no ,sistema)
    activity(_,admin, Inclui ou Altera, SideDishes: Acompanhamentos, no ,sistema)
    activity(_,admin, Inclui ou Altera, Beverages: Bebidas, no ,sistema)
    activity(_,admin, Inclui ou Altera, Desserts: Sobremesas, no ,sistema)
    activity(_,admin, Inclui ou Altera, UniqueProducts: Produtos Unicos, no ,sistema)
}

@enduml