@startuml
!include https://raw.githubusercontent.com/johthor/DomainStory-PlantUML/main/domainStory.puml

!include ProductActors.puml
!include ProductObjects.puml

Boundary("Actors", "Actors") {
    Person(nutri, "Nutricionista")
    Person(admin, "Administrador")
}

Boundary("ProductObjects", "ProductObjects") {
    Categories("Category", "Categorias")
    Snacks("Snack", "Lanches")
    Combos("Combo", "Combos")
    Ingredients("Ingredient", "Ingredientes")
    Beverages("Beverage", "Bebidas")
    Recipes("Recipe", "Receitas")
    SideDishes("SideDish", "Acompanhamentos")
    Desserts("Dessert", "Sobremesas")
    UniqueProducts("UniqueProduct", "Produtos únicos")
    Photos("Photo", "Imagens dos produtos")
    MarkRemovableItem("MarkRemovableItem", "Itens removíveis")
    MarkPlusItem("MarkPlusItem", "Itens adicionais")
    MarketBeverage("MarketBeverage", "Bebidas de mercado")
    CraftBeverage("CraftBeverage", "Bebidas artesanais")
}

@enduml