@startuml Product Management

class Product {
    + id: int
    + nome: string
    + descrição: string
    + pathImagem: string
    + categoria : Categoria
    + vendavel: bool
    + removivel: bool
    + created_at: datetime
    + updated_at: datetime
}


class Ingrediente extends Product {}

class ProductUnico extends Product {}

class ProductProduzido extends Product {}

class Lanche extends ProductProduzido {}

class Categorias {
    + id: int
    + nome: string
    + created_at: datetime
    + updated_at: datetime
}



@enduml

@startuml - Product Management - Relações de Objetos


@enduml