@startuml Product Management

class Product {
    + id: int
    + Characteristics: ProductCharacteristics
    + category : Catergory
    + sellable : bool
    + removable : bool
    + AuditDate: AuditDate      
}


class Ingredients extends Product {}

class UniqueProduct extends Product {}

class ManufacturedProduct extends Product {}

class Snacks extends ManufacturedProduct {}

class Category {
    + id: int
    + name: string
    + AuditDate: AuditDate
}

namespace ValueObjects {
    class  ProductCharacteristics {                
        + name: string
        + description: string
        + pathImage: string        
    }

    class AuditDate {
        + CreatedAt: datetime
        + UpdatedAt: datetime
    }

    class PriceComposition {
        + unitPrice: decimal
        + comboPrice: decimal
    }
}



@enduml

@startuml - Product Management - Relações de Objetos


@enduml