kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
- role: worker
- role: worker
  extraPortMappings:
  - containerPort: 30001
    hostPort: 8088
    protocol: TCP
    listenAddress: 127.0.0.1
  - containerPort: 30002
    hostPort: 8089
    protocol: TCP
    listenAddress: 127.0.0.1