# mongodb://admin:mongodbk8sHml@localhost
# NAMESPACE
apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    name: database
---
# CONFIG MAP
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-cm
  namespace: database
data:
  MONGO_INITDB_ROOT_USERNAME: admin
---
# SECRET
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-sc
  namespace: database
type: Opaque
stringData:
  MONGO_INITDB_ROOT_PASSWORD: mongodbk8sHml
---
# PERSIST VOLUME
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: database
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Delete 
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mongodb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: database
spec:
  storageClassName: local-storage
  volumeName: mongodb-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
--- 
# DEPLOYMENT
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: database
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongodb
      labels:
        app: mongodb
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: mongodb
        image: mongo
        resources:
          requests:
            memory: 512Mi
            cpu: 500m
          limits:
            ephemeral-storage: "2Gi"
            memory: 1024Mi
            cpu: 1000m
        ports:
        - containerPort: 27017
        envFrom:
        - configMapRef:
            name: mongodb-cm
        - secretRef:
            name: mongodb-sc
        volumeMounts:
        - name: mongodbdata
          mountPath: /data/db
      automountServiceAccountToken: false
      volumes:
      - name: mongodbdata
        persistentVolumeClaim:
          claimName: mongodb-pvc
--- 
# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc-np
  namespace: database
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
  - protocol: TCP 
    port: 27017
    targetPort: 27017
    nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc-cip
  namespace: database
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - protocol: TCP 
    port: 27017
    targetPort: 27017
    name: mongo
---