@startuml OrderPictoChoose
!include https://raw.githubusercontent.com/johthor/DomainStory-PlantUML/main/domainStory.puml
!include ../SharedActors.puml
!include ../SharedObjects.puml
!include OrderActors.puml
!include OrderObjects.puml

Boundary("Actors", "Actors") {
    Person(customer,"Cliente", $color=#blue)
    CustomerNonLogin(customerNotLogged,"Cliente não Identificado", $color=#OrangeRed)
    System(orderSystem,"Sistema de Pedidos")
    System(productsSystem,"Sistema Produtos", $color=#LightCoral)
    System(paymentSystem,"Broker de Pagamentos", $color=#green)
}

Boundary(objects, "Action Objects - Order Context") {    
    Basket(basket, "Produtos do Pedido")
    WebHook(webhook, "WebHook")
    OrderBasket(order, "Pedido")
    CancelOrderBasket(cancelOrder, "Cancelamento de Pedido")
    PaymentOrder(payment, "Ordem de Pagamento")
    PayOrder(pay, "Efetiva Pagamento")
    PaymentValue(paymentValue, "Valor de Pagamento")
    Info(info,"Informações")
    Calculator(calculator,"Calculo do Pedido")
    Database(database,"Banco de Dados")
    IdentityRegister(identityRegister,"Identidade")
    DatabaseRemove(databaseRemove,"Remoção de Dados")
    AddInQueue(addInQueue,"Adiciona na Fila")
    OrderStatus(orderStatus,"Status do Pedido")
    RestaurantPanel(restaurant,"Painel de Pedidos do Restaurante")
    ServiceKiosk(serviceKiosk,"Totem de Autoatendimento")
    PrintOrder(printOrder,"Impressão de Pedido")
}

@enduml

@startuml
colors
@enduml