apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-quickbite-cert
spec:
  secretName: letsencrypt-quickbite-cert
  dnsNames:
  - quickbite.com.br
  - quickbite.rabbitmq.com.br
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-homolog