# PRIMEIRO DEVEMOS INSTALAR O CERT-MANAGER NO CLUSTER
# kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.4/cert-manager.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-homolog
spec:
  selfSigned: {}
  # acme:
  #   email: rickalbbraga@gmail.com
  #     # https://acme-v02.api.letsencrypt.org/directory
  #   server: https://acme-staging-v02.api.letsencrypt.org/directory
  #   privateKeySecretRef:
  #     name: letsencrypt-quickbite-homolog
  #   solvers:
  #     - http01:
  #         ingress:
  #           class: nginx