@startuml
!include <material/cached>
!include <material/cake>
!include <material/cake_layered>
!include <material/cake_variant>
!include <material/calculator>
!include <material/calculator_off>
!include <material/calendar>
!include <material/calendar_blank>
!include <material/calendar_check>
!include <material/calendar_clock>
!include <material/calendar_multiple>
!include <material/calendar_multiple_check>
!include <material/calendar_plus>
!include <material/calendar_question>
!include <material/calendar_range>
!include <material/calendar_remove>
!include <material/calendar_select>
!include <material/calendar_text>
!include <material/calendar_today>
!include <material/call_made>
!include <material/call_merge>
!include <material/call_missed>
!include <material/call_received>
!include <material/call_split>
!include <material/camcorder>
!include <material/camcorder_box>
!include <material/camcorder_box_off>
!include <material/camcorder_off>
!include <material/camera>
!include <material/camera_burst>
!include <material/camera_enhance>
!include <material/camera_front>
!include <material/camera_front_variant>
!include <material/camera_gopro>
!include <material/camera_iris>
!include <material/camera_metering_center>
!include <material/camera_metering_matrix>
!include <material/camera_metering_partial>
!include <material/camera_metering_spot>
!include <material/camera_off>
!include <material/camera_party_mode>
!include <material/camera_rear>
!include <material/camera_rear_variant>
!include <material/camera_switch>
!include <material/camera_timer>
!include <material/cancel>
!include <material/candle>
!include <material/candycane>
!include <material/cannabis>
!include <material/car>
!include <material/caravan>
!include <material/car_battery>
!include <material/car_connected>
!include <material/car_convertable>
!include <material/cards>
!include <material/cards_outline>
!include <material/cards_playing_outline>
!include <material/cards_variant>
!include <material/car_estate>
!include <material/car_hatchback>
!include <material/car_pickup>
!include <material/carrot>
!include <material/car_side>
!include <material/car_sports>
!include <material/cart>
!include <material/cart_off>
!include <material/cart_outline>
!include <material/cart_plus>
!include <material/car_wash>
!include <material/cash>
!include <material/cash_100>
!include <material/cash_multiple>
!include <material/cash_usd>
!include <material/cast>
!include <material/cast_connected>
!include <material/castle>
!include <material/cast_off>
!include <material/cat>
!include <material/cctv>
!include <material/ceiling_light>
!include <material/cellphone>
!include <material/cellphone_android>
!include <material/cellphone_basic>
!include <material/cellphone_dock>
!include <material/cellphone_iphone>
!include <material/cellphone_link>
!include <material/cellphone_link_off>
!include <material/cellphone_settings>
!include <material/cellphone_wireless>
!include <material/certificate>
!include <material/chair_school>
!include <material/chart_arc>
!include <material/chart_areaspline>
!include <material/chart_bar>
!include <material/chart_bar_stacked>
!include <material/chart_bubble>
!include <material/chart_donut>
!include <material/chart_donut_variant>
!include <material/chart_gantt>
!include <material/chart_histogram>
!include <material/chart_line>
!include <material/chart_line_stacked>
!include <material/chart_line_variant>
!include <material/chart_pie>
!include <material/chart_scatterplot_hexbin>
!include <material/chart_timeline>
!include <material/check>
!include <material/check_all>
!include <material/check_bookmark>
!include <material/checkbox_blank>
!include <material/checkbox_blank_circle>
!include <material/checkbox_blank_circle_outline>
!include <material/checkbox_blank_outline>
!include <material/checkbox_marked>
!include <material/checkbox_marked_circle>
!include <material/checkbox_marked_circle_outline>
!include <material/checkbox_marked_outline>
!include <material/checkbox_multiple_blank>
!include <material/checkbox_multiple_blank_circle>
!include <material/checkbox_multiple_blank_circle_outline>
!include <material/checkbox_multiple_blank_outline>
!include <material/checkbox_multiple_marked>
!include <material/checkbox_multiple_marked_circle>
!include <material/checkbox_multiple_marked_circle_outline>
!include <material/checkbox_multiple_marked_outline>
!include <material/check_circle>
!include <material/check_circle_outline>
!include <material/checkerboard>
!include <material/chemical_weapon>
!include <material/chevron_double_down>
!include <material/chevron_double_left>
!include <material/chevron_double_right>
!include <material/chevron_double_up>
!include <material/chevron_down>
!include <material/chevron_left>
!include <material/chevron_right>
!include <material/chevron_up>
!include <material/chili_hot>
!include <material/chili_medium>
!include <material/chili_mild>
!include <material/chip>
!include <material/church>
!include <material/circle>
!include <material/circle_outline>
!include <material/cisco_webex>
!include <material/city>
!include <material/clapperboard>
!include <material/clipboard>
!include <material/clipboard_account>
!include <material/clipboard_alert>
!include <material/clipboard_arrow_down>
!include <material/clipboard_arrow_left>
!include <material/clipboard_check>
!include <material/clipboard_flow>
!include <material/clipboard_outline>
!include <material/clipboard_plus>
!include <material/clipboard_text>
!include <material/clippy>
!include <material/clock>
!include <material/clock_alert>
!include <material/clock_end>
!include <material/clock_fast>
!include <material/clock_in>
!include <material/clock_out>
!include <material/clock_start>
!include <material/close>
!include <material/close_circle>
!include <material/close_circle_outline>
!include <material/closed_caption>
!include <material/close_network>
!include <material/close_octagon>
!include <material/close_octagon_outline>
!include <material/close_outline>
!include <material/cloud>
!include <material/cloud_braces>
!include <material/cloud_check>
!include <material/cloud_circle>
!include <material/cloud_download>
!include <material/cloud_off_outline>
!include <material/cloud_outline>
!include <material/cloud_print>
!include <material/cloud_print_outline>
!include <material/cloud_sync>
!include <material/cloud_tags>
!include <material/cloud_upload>
!include <material/clover>
!include <material/code_array>
!include <material/code_braces>
!include <material/code_brackets>
!include <material/code_equal>
!include <material/code_greater_than>
!include <material/code_greater_than_or_equal>
!include <material/code_less_than>
!include <material/code_less_than_or_equal>
!include <material/code_not_equal>
!include <material/code_not_equal_variant>
!include <material/code_parentheses>
!include <material/codepen>
!include <material/code_string>
!include <material/code_tags>
!include <material/code_tags_check>
!include <material/coffee>
!include <material/coffee_outline>
!include <material/coffee_to_go>
!include <material/coin>
!include <material/coins>
!include <material/collage>
!include <material/color_helper>
!include <material/comment>
!include <material/comment_account>
!include <material/comment_account_outline>
!include <material/comment_alert>
!include <material/comment_alert_outline>
!include <material/comment_check>
!include <material/comment_check_outline>
!include <material/comment_multiple_outline>
!include <material/comment_outline>
!include <material/comment_plus_outline>
!include <material/comment_processing>
!include <material/comment_processing_outline>
!include <material/comment_question>
!include <material/comment_question_outline>
!include <material/comment_remove>
!include <material/comment_remove_outline>
!include <material/comment_text>
!include <material/comment_text_outline>
!include <material/compare>
!include <material/compass>
!include <material/compass_outline>
!include <material/console>
!include <material/console_line>
!include <material/contact_mail>
!include <material/contacts>
!include <material/content_copy>
!include <material/content_cut>
!include <material/content_duplicate>
!include <material/content_paste>
!include <material/content_save>
!include <material/content_save_all>
!include <material/content_save_outline>
!include <material/content_save_settings>
!include <material/contrast>
!include <material/contrast_box>
!include <material/contrast_circle>
!include <material/controller_xbox>
!include <material/cookie>
!include <material/copyright>
!include <material/corn>
!include <material/counter>
!include <material/cow>
!include <material/creation>
!include <material/credit_card>
!include <material/credit_card_multiple>
!include <material/credit_card_off>
!include <material/credit_card_plus>
!include <material/credit_card_scan>
!include <material/crop>
!include <material/crop_free>
!include <material/crop_landscape>
!include <material/crop_portrait>
!include <material/crop_rotate>
!include <material/crop_square>
!include <material/crosshairs>
!include <material/crosshairs_gps>
!include <material/crown>
!include <material/cube>
!include <material/cube_outline>
!include <material/cube_send>
!include <material/cube_unfolded>
!include <material/cup>
!include <material/cup_off>
!include <material/cup_water>
!include <material/currency_btc>
!include <material/currency_chf>
!include <material/currency_cny>
!include <material/currency_eth>
!include <material/currency_eur>
!include <material/currency_gbp>
!include <material/currency_inr>
!include <material/currency_jpy>
!include <material/currency_krw>
!include <material/currency_ngn>
!include <material/currency_rub>
!include <material/currency_sign>
!include <material/currency_try>
!include <material/currency_twd>
!include <material/currency_usd>
!include <material/currency_usd_off>
!include <material/cursor_default>
!include <material/cursor_default_outline>
!include <material/cursor_move>
!include <material/cursor_pointer>
!include <material/cursor_text>
listsprites
@enduml