@startuml


!include <material/access_point>
!include <material/access_point_network>
!include <material/account>
!include <material/account_alert>
!include <material/account_box>
!include <material/account_box_outline>
!include <material/account_card_details>
!include <material/account_check>
!include <material/account_circle>
!include <material/account_convert>
!include <material/account_edit>
!include <material/account_key>
!include <material/account_location>
!include <material/account_minus>
!include <material/account_multiple>
!include <material/account_multiple_minus>
!include <material/account_multiple_outline>
!include <material/account_multiple_plus>
!include <material/account_multiple_plus_outline>
!include <material/account_network>
!include <material/account_off>
!include <material/account_outline>
!include <material/account_plus>
!include <material/account_plus_outline>
!include <material/account_remove>
!include <material/account_search>
!include <material/account_settings>
!include <material/account_settings_variant>
!include <material/account_switch>
!include <material/adjust>
!include <material/airballoon>
!include <material/air_conditioner>
!include <material/airplane>
!include <material/airplane_landing>
!include <material/airplane_off>
!include <material/airplane_takeoff>
!include <material/airplay>
!include <material/alarm>
!include <material/alarm_bell>
!include <material/alarm_check>
!include <material/alarm_light>
!include <material/alarm_multiple>
!include <material/alarm_off>
!include <material/alarm_plus>
!include <material/alarm_snooze>
!include <material/album>
!include <material/alert>
!include <material/alert_box>
!include <material/alert_circle>
!include <material/alert_circle_outline>
!include <material/alert_decagram>
!include <material/alert_octagon>
!include <material/alert_octagram>
!include <material/alert_outline>
!include <material/all_inclusive>
!include <material/allo>
!include <material/alpha>
!include <material/alphabetical>
!include <material/altimeter>
!include <material/amazon>
!include <material/amazon_clouddrive>
!include <material/ambulance>
!include <material/amplifier>
!include <material/anchor>
!include <material/android>
!include <material/android_debug_bridge>
!include <material/android_head>
!include <material/android_studio>
!include <material/angular>
!include <material/angularjs>
!include <material/animation>
!include <material/apple>
!include <material/apple_finder>
!include <material/apple_ios>
!include <material/apple_keyboard_caps>
!include <material/apple_keyboard_command>
!include <material/apple_keyboard_control>
!include <material/apple_keyboard_option>
!include <material/apple_keyboard_shift>
!include <material/apple_mobileme>
!include <material/apple_safari>
!include <material/application>
!include <material/appnet>
!include <material/approval>
!include <material/apps>
!include <material/archive>
!include <material/arrange_bring_forward>
!include <material/arrange_bring_to_front>
!include <material/arrange_send_backward>
!include <material/arrange_send_to_back>
!include <material/arrow_all>
!include <material/arrow_bottom_left>
!include <material/arrow_bottom_right>
!include <material/arrow_collapse>
!include <material/arrow_collapse_all>
!include <material/arrow_collapse_down>
!include <material/arrow_collapse_left>
!include <material/arrow_collapse_right>
!include <material/arrow_collapse_up>
!include <material/arrow_down>
!include <material/arrow_down_bold>
!include <material/arrow_down_bold_box>
!include <material/arrow_down_bold_box_outline>
!include <material/arrow_down_bold_circle>
!include <material/arrow_down_bold_circle_outline>
!include <material/arrow_down_bold_hexagon_outline>
!include <material/arrow_down_box>
!include <material/arrow_down_drop>
!include <material/arrow_down_drop_circle>
!include <material/arrow_down_drop_circle_outline>
!include <material/arrow_down_thick>
!include <material/arrow_expand>
!include <material/arrow_expand_all>
!include <material/arrow_expand_down>
!include <material/arrow_expand_left>
!include <material/arrow_expand_right>
!include <material/arrow_expand_up>
!include <material/arrow_left>
!include <material/arrow_left_bold>
!include <material/arrow_left_bold_box>
!include <material/arrow_left_bold_box_outline>
!include <material/arrow_left_bold_circle>
!include <material/arrow_left_bold_circle_outline>
!include <material/arrow_left_bold_hexagon_outline>
!include <material/arrow_left_box>
!include <material/arrow_left_drop_circle>
!include <material/arrow_left_drop_circle_outline>
!include <material/arrow_left_thick>
!include <material/arrow_right>
!include <material/arrow_right_bold>
!include <material/arrow_right_bold_box>
!include <material/arrow_right_bold_box_outline>
!include <material/arrow_right_bold_circle>
!include <material/arrow_right_bold_circle_outline>
!include <material/arrow_right_bold_hexagon_outline>
!include <material/arrow_right_box>
!include <material/arrow_right_drop_circle>
!include <material/arrow_right_drop_circle_outline>
!include <material/arrow_right_thick>
!include <material/arrow_top_left>
!include <material/arrow_top_right>
!include <material/arrow_up>
!include <material/arrow_up_bold>
!include <material/arrow_up_bold_box>
!include <material/arrow_up_bold_box_outline>
!include <material/arrow_up_bold_circle>
!include <material/arrow_up_bold_circle_outline>
!include <material/arrow_up_bold_hexagon_outline>
!include <material/arrow_up_box>
!include <material/arrow_up_drop_circle>
!include <material/arrow_up_drop_circle_outline>
!include <material/arrow_up_thick>
!include <material/artist>
!include <material/assistant>
!include <material/asterisk>
!include <material/at>
!include <material/atlassian>
!include <material/atom>
!include <material/attachment>
!include <material/audiobook>
!include <material/auto_fix>
!include <material/autorenew>
!include <material/auto_upload>
!include <material/av_timer>
!include <material/azure>
listsprites
@enduml