@startuml
!include <material/sale>
!include <material/sass>
!include <material/satellite>
!include <material/satellite_variant>
!include <material/saxophone>
!include <material/scale>
!include <material/scale_balance>
!include <material/scale_bathroom>
!include <material/scanner>
!include <material/school>
!include <material/screen_rotation>
!include <material/screen_rotation_lock>
!include <material/screwdriver>
!include <material/script>
!include <material/sd>
!include <material/seal>
!include <material/search_web>
!include <material/seat_flat>
!include <material/seat_flat_angled>
!include <material/seat_individual_suite>
!include <material/seat_legroom_extra>
!include <material/seat_legroom_normal>
!include <material/seat_legroom_reduced>
!include <material/seat_recline_extra>
!include <material/seat_recline_normal>
!include <material/security>
!include <material/security_home>
!include <material/security_network>
!include <material/select>
!include <material/select_all>
!include <material/select_inverse>
!include <material/selection>
!include <material/selection_off>
!include <material/select_off>
!include <material/send>
!include <material/send_secure>
!include <material/serial_port>
!include <material/server>
!include <material/server_minus>
!include <material/server_network>
!include <material/server_network_off>
!include <material/server_off>
!include <material/server_plus>
!include <material/server_remove>
!include <material/server_security>
!include <material/set_all>
!include <material/set_center>
!include <material/set_center_right>
!include <material/set_left>
!include <material/set_left_center>
!include <material/set_left_right>
!include <material/set_none>
!include <material/set_right>
!include <material/settings>
!include <material/settings_box>
!include <material/shape>
!include <material/shape_circle_plus>
!include <material/shape_outline>
!include <material/shape_plus>
!include <material/shape_polygon_plus>
!include <material/shape_rectangle_plus>
!include <material/shape_square_plus>
!include <material/share>
!include <material/share_variant>
!include <material/shield>
!include <material/shield_half_full>
!include <material/shield_outline>
!include <material/ship_wheel>
!include <material/shopping>
!include <material/shopping_music>
!include <material/shovel>
!include <material/shovel_off>
!include <material/shredder>
!include <material/shuffle>
!include <material/shuffle_disabled>
!include <material/shuffle_variant>
!include <material/sigma>
!include <material/sigma_lower>
!include <material/signal>
!include <material/signal_2g>
!include <material/signal_3g>
!include <material/signal_4g>
!include <material/signal_hspa>
!include <material/signal_hspa_plus>
!include <material/signal_off>
!include <material/signal_variant>
!include <material/sign_caution>
!include <material/sign_direction>
!include <material/sign_text>
!include <material/silverware>
!include <material/silverware_fork>
!include <material/silverware_spoon>
!include <material/silverware_variant>
!include <material/sim>
!include <material/sim_alert>
!include <material/sim_off>
!include <material/sitemap>
!include <material/skip_backward>
!include <material/skip_forward>
!include <material/skip_next>
!include <material/skip_next_circle>
!include <material/skip_next_circle_outline>
!include <material/skip_previous>
!include <material/skip_previous_circle>
!include <material/skip_previous_circle_outline>
!include <material/skull>
!include <material/skype>
!include <material/skype_business>
!include <material/slack>
!include <material/sleep>
!include <material/sleep_off>
!include <material/smoking>
!include <material/smoking_off>
!include <material/snapchat>
!include <material/snowflake>
!include <material/snowman>
!include <material/soccer>
!include <material/soccer_field>
!include <material/sofa>
!include <material/solid>
!include <material/sort>
!include <material/sort_alphabetical>
!include <material/sort_ascending>
!include <material/sort_descending>
!include <material/sort_numeric>
!include <material/sort_variant>
!include <material/soundcloud>
!include <material/source_branch>
!include <material/source_commit>
!include <material/source_commit_end>
!include <material/source_commit_end_local>
!include <material/source_commit_local>
!include <material/source_commit_next_local>
!include <material/source_commit_start>
!include <material/source_commit_start_next_local>
!include <material/source_fork>
!include <material/source_merge>
!include <material/source_pull>
!include <material/soy_sauce>
!include <material/speaker>
!include <material/speaker_off>
!include <material/speaker_wireless>
!include <material/speedometer>
!include <material/spellcheck>
!include <material/spotify>
!include <material/spotlight>
!include <material/spotlight_beam>
!include <material/spray>
!include <material/spreadsheet>
!include <material/square>
!include <material/square_inc>
!include <material/square_inc_cash>
!include <material/square_outline>
!include <material/square_root>
!include <material/stackexchange>
!include <material/stackoverflow>
!include <material/stadium>
!include <material/stairs>
!include <material/standard_definition>
!include <material/star>
!include <material/star_circle>
!include <material/star_half>
!include <material/star_of_david>
!include <material/star_off>
!include <material/star_outline>
!include <material/steam>
!include <material/steering>
!include <material/step_backward>
!include <material/step_backward_2>
!include <material/step_forward>
!include <material/step_forward_2>
!include <material/stethoscope>
!include <material/sticker>
!include <material/sticker_emoji>
!include <material/stocking>
!include <material/stop>
!include <material/stop_circle>
!include <material/stop_circle_outline>
!include <material/store>
!include <material/store_24_hour>
!include <material/stove>
!include <material/subdirectory_arrow_left>
!include <material/subdirectory_arrow_right>
!include <material/subway>
!include <material/subway_variant>
!include <material/summit>
!include <material/sunglasses>
!include <material/surround_sound>
!include <material/surround_sound_2_0>
!include <material/surround_sound_3_1>
!include <material/surround_sound_5_1>
!include <material/surround_sound_7_1>
!include <material/svg>
!include <material/swap_horizontal>
!include <material/swap_vertical>
!include <material/swim>
!include <material/switch>
!include <material/sword>
!include <material/sword_cross>
!include <material/sync>
!include <material/sync_alert>
!include <material/sync_off>

listsprites
@enduml