@startuml
!include <material/face>
!include <material/facebook>
!include <material/facebook_box>
!include <material/facebook_messenger>
!include <material/face_profile>
!include <material/factory>
!include <material/fan>
!include <material/fan_off>
!include <material/fast_forward>
!include <material/fast_forward_outline>
!include <material/fax>
!include <material/feather>
!include <material/ferry>
!include <material/file>
!include <material/file_account>
!include <material/file_chart>
!include <material/file_check>
!include <material/file_cloud>
!include <material/file_delimited>
!include <material/file_document>
!include <material/file_document_box>
!include <material/file_excel>
!include <material/file_excel_box>
!include <material/file_export>
!include <material/file_find>
!include <material/file_hidden>
!include <material/file_image>
!include <material/file_image_box>
!include <material/file_import>
!include <material/file_lock>
!include <material/file_move>
!include <material/file_multiple>
!include <material/file_music>
!include <material/file_outline>
!include <material/file_pdf>
!include <material/file_pdf_box>
!include <material/file_percent>
!include <material/file_plus>
!include <material/file_powerpoint>
!include <material/file_powerpoint_box>
!include <material/file_presentation_box>
!include <material/file_restore>
!include <material/file_send>
!include <material/file_tree>
!include <material/file_video>
!include <material/file_word>
!include <material/file_word_box>
!include <material/file_xml>
!include <material/fill>
!include <material/film>
!include <material/filmstrip>
!include <material/filmstrip_off>
!include <material/filter>
!include <material/filter_outline>
!include <material/filter_remove>
!include <material/filter_remove_outline>
!include <material/filter_variant>
!include <material/find_replace>
!include <material/fingerprint>
!include <material/fire>
!include <material/fish>
!include <material/flag>
!include <material/flag_checkered>
!include <material/flag_checkered_variant>
!include <material/flag_outline>
!include <material/flag_outline_variant>
!include <material/flag_triangle>
!include <material/flag_variant>
!include <material/flash>
!include <material/flash_auto>
!include <material/flash_circle>
!include <material/flashlight>
!include <material/flashlight_off>
!include <material/flash_off>
!include <material/flash_outline>
!include <material/flash_red_eye>
!include <material/flask>
!include <material/flask_empty>
!include <material/flask_empty_outline>
!include <material/flask_outline>
!include <material/flattr>
!include <material/flickr_after>
!include <material/flickr_before>
!include <material/flip_to_back>
!include <material/flip_to_front>
!include <material/floor_plan>
!include <material/floppy>
!include <material/flower>
!include <material/folder>
!include <material/folder_account>
!include <material/folder_download>
!include <material/folder_google_drive>
!include <material/folder_image>
!include <material/folder_lock>
!include <material/folder_lock_open>
!include <material/folder_move>
!include <material/folder_multiple>
!include <material/folder_multiple_image>
!include <material/folder_multiple_outline>
!include <material/folder_open>
!include <material/folder_outline>
!include <material/folder_outline_lock>
!include <material/folder_plus>
!include <material/folder_remove>
!include <material/folder_star>
!include <material/folder_upload>
!include <material/font_awesome>
!include <material/food>
!include <material/food_apple>
!include <material/food_croissant>
!include <material/food_fork_drink>
!include <material/food_off>
!include <material/food_variant>
!include <material/football>
!include <material/football_australian>
!include <material/football_helmet>
!include <material/footer>
!include <material/forklift>
!include <material/format_align_bottom>
!include <material/format_align_center>
!include <material/format_align_justify>
!include <material/format_align_left>
!include <material/format_align_middle>
!include <material/format_align_right>
!include <material/format_align_top>
!include <material/format_annotation_plus>
!include <material/format_bold>
!include <material/format_clear>
!include <material/format_color>
!include <material/format_color_fill>
!include <material/format_color_text>
!include <material/format_float_center>
!include <material/format_float_left>
!include <material/format_float_none>
!include <material/format_float_right>
!include <material/format_font>
!include <material/format_header_1>
!include <material/format_header_2>
!include <material/format_header_3>
!include <material/format_header_4>
!include <material/format_header_5>
!include <material/format_header_6>
!include <material/format_header_decrease>
!include <material/format_header_down>
!include <material/format_header_equal>
!include <material/format_header_increase>
!include <material/format_header_pound>
!include <material/format_header_up>
!include <material/format_horizontal_align_center>
!include <material/format_horizontal_align_left>
!include <material/format_horizontal_align_right>
!include <material/format_indent_decrease>
!include <material/format_indent_increase>
!include <material/format_italic>
!include <material/format_line_spacing>
!include <material/format_line_style>
!include <material/format_line_weight>
!include <material/format_list_bulleted>
!include <material/format_list_bulleted_type>
!include <material/format_list_checks>
!include <material/format_list_numbers>
!include <material/format_page_break>
!include <material/format_paint>
!include <material/format_paragraph>
!include <material/format_pilcrow>
!include <material/format_quote_close>
!include <material/format_quote_open>
!include <material/format_rotate_90>
!include <material/format_section>
!include <material/format_size>
!include <material/format_strikethrough>
!include <material/format_strikethrough_variant>
!include <material/format_subscript>
!include <material/format_superscript>
!include <material/format_text>
!include <material/format_textdirection_l_to_r>
!include <material/format_textdirection_r_to_l>
!include <material/format_title>
!include <material/format_underline>
!include <material/format_vertical_align_bottom>
!include <material/format_vertical_align_center>
!include <material/format_vertical_align_top>
!include <material/format_wrap_inline>
!include <material/format_wrap_square>
!include <material/format_wrap_tight>
!include <material/format_wrap_top_bottom>
!include <material/forum>
!include <material/forum_outline>
!include <material/forward>
!include <material/foursquare>
!include <material/fridge>
!include <material/fridge_filled>
!include <material/fridge_filled_bottom>
!include <material/fridge_filled_top>
!include <material/fuel>
!include <material/fullscreen>
!include <material/fullscreen_exit>
!include <material/function>

listsprites
@enduml