@startuml
!include <material/account_card_details>
!include <material/beer>
!include <material/backburger>
!include <material/basket>
!include <material/basketball>
!include <material/basket_fill>
!include <material/basket_unfill> 
!include <material/bowl>
!include <material/calculator>
!include <material/cart>
!include <material/cart_off>
!include <material/cart_outline>
!include <material/cart_plus>
!include <material/cash>
!include <material/cash_100>
!include <material/cash_multiple>
!include <material/cash_usd>
!include <material/close>
!include <material/close_circle>
!include <material/close_circle_outline>
!include <material/close_octagon>
!include <material/close_octagon_outline>
!include <material/close_outline>
!include <material/cup>
!include <material/cup_off>
!include <material/cup_water>
!include <material/data>
!include <material/database>
!include <material/database_minus>
!include <material/database_plus>
!include <material/delete>
!include <material/delete_circle>
!include <material/delete_empty>
!include <material/delete_forever>
!include <material/delete_restore>
!include <material/delete_sweep>
!include <material/delete_variant>
!include <material/email>
!include <material/ice_cream> 
'!include <material/forest>
!include <material/food>
!include <material/food_apple>
!include <material/food_croissant>
!include <material/food_fork_drink>
!include <material/food_off>
!include <material/food_variant>
!include <material/glass_mug>
!include <material/hamburger>
!include <material/hook>
!include <material/hook_off>
!include <material/label>
!include <material/label_outline>
!include <material/library_books>
!include <material/minus>
!include <material/minus_box>
!include <material/minus_box_outline>
!include <material/minus_circle>
!include <material/minus_circle_outline>
!include <material/numeric>
!include <material/nutrition>
!include <material/package_variant>
!include <material/package_variant_closed> 
!include <material/playlist_check>
!include <material/playlist_minus>
!include <material/playlist_play>
!include <material/playlist_plus>
!include <material/playlist_remove>
!include <material/plus>
!include <material/plus_box>
!include <material/plus_box_outline>
!include <material/plus_circle>
!include <material/plus_circle_multiple_outline>
!include <material/plus_circle_outline>
!include <material/plus_network>
!include <material/plus_one>
!include <material/plus_outline>
!include <material/popcorn>
!include <material/pot>
!include <material/pot_mix>
!include <material/priority_high>
!include <material/priority_low>
!include <material/publish>
!include <material/qrcode>
!include <material/qrcode_scan> 
!include <material/receipt>
!include <material/redo>
!include <material/redo_variant>
!include <material/rice>
!include <material/road_variant>
!include <material/silverware>
!include <material/silverware_fork>
!include <material/silverware_spoon>
!include <material/silverware_variant>
!include <material/television_guide>
!include <material/textbox>
!include <material/textbox_password>
!include <material/view_quilt>
listsprites
@enduml