@startuml
!include <material/nature>
!include <material/nature_people>
!include <material/navigation>
!include <material/near_me>
!include <material/needle>
!include <material/nest_protect>
!include <material/nest_thermostat>
!include <material/netflix>
!include <material/network>
!include <material/new_box>
!include <material/newspaper>
!include <material/nfc>
!include <material/nfc_tap>
!include <material/nfc_variant>
!include <material/ninja>
!include <material/nintendo_switch>
!include <material/no>
!include <material/nodejs>
!include <material/note>
!include <material/notebook>
!include <material/note_multiple>
!include <material/note_multiple_outline>
!include <material/note_outline>
!include <material/note_plus>
!include <material/note_plus_outline>
!include <material/not_equal>
!include <material/note_text>
!include <material/notification_clear_all>
!include <material/npm>
!include <material/nuke>
!include <material/null>
!include <material/numeric>
!include <material/numeric_0_box>
!include <material/numeric_0_box_multiple_outline>
!include <material/numeric_0_box_outline>
!include <material/numeric_1_box>
!include <material/numeric_1_box_multiple_outline>
!include <material/numeric_1_box_outline>
!include <material/numeric_2_box>
!include <material/numeric_2_box_multiple_outline>
!include <material/numeric_2_box_outline>
!include <material/numeric_3_box>
!include <material/numeric_3_box_multiple_outline>
!include <material/numeric_3_box_outline>
!include <material/numeric_4_box>
!include <material/numeric_4_box_multiple_outline>
!include <material/numeric_4_box_outline>
!include <material/numeric_5_box>
!include <material/numeric_5_box_multiple_outline>
!include <material/numeric_5_box_outline>
!include <material/numeric_6_box>
!include <material/numeric_6_box_multiple_outline>
!include <material/numeric_6_box_outline>
!include <material/numeric_7_box>
!include <material/numeric_7_box_multiple_outline>
!include <material/numeric_7_box_outline>
!include <material/numeric_8_box>
!include <material/numeric_8_box_multiple_outline>
!include <material/numeric_8_box_outline>
!include <material/numeric_9_box>
!include <material/numeric_9_box_multiple_outline>
!include <material/numeric_9_box_outline>
!include <material/numeric_9_plus_box>
!include <material/numeric_9_plus_box_multiple_outline>
!include <material/numeric_9_plus_box_outline>
!include <material/nut>
!include <material/nutrition>

listsprites
@enduml