!include https://raw.githubusercontent.com/johthor/DomainStory-PlantUML/main/domainStory.puml

!include <material/cart_outline>
!unquoted procedure Basket($name, $label = "", $color = "", $scale = "", $note = "")
     Object("Basket", "$ma_cart_outline", $name, $label, $color, $scale, $note)
!endprocedure

!include <material/database>
!unquoted procedure Database($name, $label = "", $color = "", $scale = "", $note = "")
     Object("Database", "$ma_database", $name, $label, $color, $scale, $note)
!endprocedure

!include <material/database_minus>
!unquoted procedure DatabaseRemove($name, $label = "", $color = "", $scale = "", $note = "")
     Object("DatabaseRemove", "$ma_database_minus", $name, $label, $color, $scale, $note)
!endprocedure

!include <material/database_plus>
!unquoted procedure DatabaseAdd($name, $label = "", $color = "", $scale = "", $note = "")
     Object("DatabaseAdd", "$ma_database_plus", $name, $label, $color, $scale, $note)
!endprocedure

!include <material/calculator>
!unquoted procedure Calculator($name, $label = "", $color = "", $scale = "", $note = "")
     Object("Calculator", "$ma_calculator", $name, $label, $color, $scale, $note)
!endprocedure

!include <material/numeric>
!unquoted procedure IdentityRegister($name, $label = "", $color = "", $scale = "", $note = "")
     Object("IdentityRegister", "$ma_numeric", $name, $label, $color, $scale, $note)
!endprocedure


!include <material/account_card_details>
!unquoted procedure AccountCardDetails($name, $label = "", $color = "", $scale = "", $note = "")
     Object("AccountCardDetails", "$ma_account_card_details", $name, $label, $color, $scale, $note)
!endprocedure

!include <material/email>
!unquoted procedure Email($name, $label = "", $color = "", $scale = "", $note = "")
     Object("Email", "$ma_email", $name, $label, $color, $scale, $note)
!endprocedure



!include <material/table_column_plus_after>
!unquoted procedure AddInQueue($name, $label = "", $color = "", $scale = "", $note = "")
     Object("AddInQueue", "$ma_table_column_plus_after", $name, $label, $color, $scale, $note)
!endprocedure


!include <material/table_column>
!unquoted procedure Queue($name, $label = "", $color = "", $scale = "", $note = "")
     Object("Queue", "$ma_table_column", $name, $label, $color, $scale, $note)
!endprocedure

!include <material/table_column_remove>
!unquoted procedure RemoveFromQueue($name, $label = "", $color = "", $scale = "", $note = "")
     Object("Queue", "$ma_table_column_remove", $name, $label, $color, $scale, $note)
!endprocedure

!include <material/view_sequential>
!unquoted procedure RestaurantPanel($name, $label = "", $color = "", $scale = "", $note = "")
    Object("RestaurantPanel", "$ma_view_sequential", $name, $label, $color, $scale, $note)
!endprocedure

!include <material/tag_text_outline>
!unquoted procedure OrderStatus($name, $label = "", $color = "", $scale = "", $note = "")
    Object("OrderStatus", "$ma_tag_text_outline", $name, $label, $color, $scale, $note)
!endprocedure

!include <material/cart>
!unquoted procedure OrderBasket($name, $label = "", $color = "", $scale = "", $note = "")
     Object("OrderBasket", "$ma_cart", $name, $label, $color, $scale, $note)
!endprocedure

!include <material/package_variant_closed> 
!unquoted procedure Package($name, $label = "", $color = "", $scale = "", $note = "")
    Object("PackagePrepare", "$ma_package_variant_closed", $name, $label, $color, $scale, $note)
!endprocedure