@startuml Products Scenarios - Domain Storytelling
!include https://raw.githubusercontent.com/tmorin/plantuml-libs/master/distribution/domainstorytelling/single.puml
 
Title("Admin interats with Produtcs", "")
 
include('domainstorytelling/Actor/User')
include('fontawesome-6/Regular/CommentDots')
include('fontawesome-6/Regular/Image')
 
User('Admin', "Admin")
User('developer', "developer")
CommentDots('domain_story_a', 'domain story')
Image('domain_story_b', 'domain story')
 
domain_expert -r-> domain_story_a : Activity("01", "tells")
domain_story_a -r-> developer : Activity("", "to")
 
developer -d-> domain_story_b : Activity("02", "draws")
 
domain_expert -d-> domain_story_b : Activity("03", "reads and corrects")
 
@enduml

@startuml
!include https://raw.githubusercontent.com/johthor/DomainStory-PlantUML/main/domainStory.puml
'!include ../domainStory.puml

' Actors
!include <material/store>
!unquoted procedure Merchant($name, $label = "", $color = "", $scale = "", $note = "")
    Actor("Merchant", "$ma_store", $name, $label, $color, $scale, $note)
!endprocedure

!include <material/crown>
!unquoted procedure Customer($name, $label = "", $color = "", $scale = "", $note = "")
    Actor("Customer", "$ma_crown", $name, $label, $color, $scale, $note)
!endprocedure

!include <material/settings_box>
!unquoted procedure Process($name, $label = "", $color = "", $scale = "", $note = "")
    Actor("Process", "$ma_settings_box", $name, $label, $color, $scale, $note)
!endprocedure

!include <material/account_alert>
!unquoted procedure AccountAlert($name, $label = "", $color = "", $scale = "", $note = "")
    Actor("AccountAlert", "$ma_account_alert", $name, $label, $color, $scale, $note)
!endprocedure



'!include <material/account_cash>
' !unquoted procedure AccountBoxEditOutline($name, $label = "", $color = "", $scale = "", $note = "")
'     Object("AccountBoxEditOutline", "$ma_account_box_edit_outline", $name, $label, $color, $scale, $note)
' !endprocedure
' !unquoted procedure Document($name, $label = "", $color = "", $scale = "", $note = "")
'     Object("Document", "$documentSprite", $name, $label, $color, $scale, $note)
' !endprocedure

Boundary(actors) {
    Merchant(Merchant)
    Customer(Customer)
    Process(Process)
    AccountAlert(AccountAlert)
    
}
@enduml



@startuml
!include <material/common>

!include <material/access_point>
!include <material/access_point_network>
!include <material/account>
!include <material/account_alert>
!include <material/account_box>
!include <material/account_box_outline>
!include <material/account_card_details>
!include <material/account_check>
!include <material/account_circle>
!include <material/account_convert>
!include <material/account_edit>
!include <material/account_key>
!include <material/account_location>
!include <material/account_minus>
!include <material/account_multiple>
!include <material/account_multiple_minus>
!include <material/account_multiple_outline>
!include <material/account_multiple_plus>
!include <material/account_multiple_plus_outline>
!include <material/account_network>
!include <material/account_off>
!include <material/account_outline>
!include <material/account_plus>
!include <material/account_plus_outline>
!include <material/account_remove>
!include <material/account_search>
!include <material/account_settings>
!include <material/account_settings_variant>
!include <material/account_switch>
!include <material/adjust>
!include <material/airballoon>
!include <material/air_conditioner>
!include <material/airplane>
!include <material/airplane_landing>
!include <material/airplane_off>
!include <material/airplane_takeoff>
!include <material/airplay>
!include <material/alarm>
!include <material/alarm_bell>
!include <material/alarm_check>
!include <material/alarm_light>
!include <material/alarm_multiple>
!include <material/alarm_off>
!include <material/alarm_plus>
!include <material/alarm_snooze>
!include <material/album>
!include <material/alert>
!include <material/alert_box>
!include <material/alert_circle>
!include <material/alert_circle_outline>
!include <material/alert_decagram>
!include <material/alert_octagon>
!include <material/alert_octagram>
!include <material/alert_outline>
!include <material/all_inclusive>
!include <material/allo>
!include <material/alpha>
!include <material/alphabetical>
!include <material/altimeter>
!include <material/amazon>
!include <material/amazon_clouddrive>
!include <material/ambulance>
!include <material/amplifier>
!include <material/anchor>
!include <material/android>
!include <material/android_debug_bridge>
!include <material/android_head>
!include <material/android_studio>
!include <material/angular>
!include <material/angularjs>
!include <material/animation>
!include <material/apple>
!include <material/apple_finder>
!include <material/apple_ios>
!include <material/apple_keyboard_caps>
!include <material/apple_keyboard_command>
!include <material/apple_keyboard_control>
!include <material/apple_keyboard_option>
!include <material/apple_keyboard_shift>
!include <material/apple_mobileme>
!include <material/apple_safari>
!include <material/application>
!include <material/appnet>
!include <material/approval>
!include <material/apps>
!include <material/archive>
!include <material/arrange_bring_forward>
!include <material/arrange_bring_to_front>
!include <material/arrange_send_backward>
!include <material/arrange_send_to_back>
!include <material/arrow_all>
!include <material/arrow_bottom_left>
!include <material/arrow_bottom_right>
!include <material/arrow_collapse>
!include <material/arrow_collapse_all>
!include <material/arrow_collapse_down>
!include <material/arrow_collapse_left>
!include <material/arrow_collapse_right>
!include <material/arrow_collapse_up>
!include <material/arrow_down>
!include <material/arrow_down_bold>
!include <material/arrow_down_bold_box>
!include <material/arrow_down_bold_box_outline>
!include <material/arrow_down_bold_circle>
!include <material/arrow_down_bold_circle_outline>
!include <material/arrow_down_bold_hexagon_outline>
!include <material/arrow_down_box>
!include <material/arrow_down_drop>
!include <material/arrow_down_drop_circle>
!include <material/arrow_down_drop_circle_outline>
!include <material/arrow_down_thick>
!include <material/arrow_expand>
!include <material/arrow_expand_all>
!include <material/arrow_expand_down>
!include <material/arrow_expand_left>
!include <material/arrow_expand_right>
!include <material/arrow_expand_up>
!include <material/arrow_left>
!include <material/arrow_left_bold>
!include <material/arrow_left_bold_box>
!include <material/arrow_left_bold_box_outline>
!include <material/arrow_left_bold_circle>
!include <material/arrow_left_bold_circle_outline>
!include <material/arrow_left_bold_hexagon_outline>
!include <material/arrow_left_box>
!include <material/arrow_left_drop_circle>
!include <material/arrow_left_drop_circle_outline>
!include <material/arrow_left_thick>
!include <material/arrow_right>
!include <material/arrow_right_bold>
!include <material/arrow_right_bold_box>
!include <material/arrow_right_bold_box_outline>
!include <material/arrow_right_bold_circle>
!include <material/arrow_right_bold_circle_outline>
!include <material/arrow_right_bold_hexagon_outline>
!include <material/arrow_right_box>
!include <material/arrow_right_drop_circle>
!include <material/arrow_right_drop_circle_outline>
!include <material/arrow_right_thick>
!include <material/arrow_top_left>
!include <material/arrow_top_right>
!include <material/arrow_up>
!include <material/arrow_up_bold>
!include <material/arrow_up_bold_box>
!include <material/arrow_up_bold_box_outline>
!include <material/arrow_up_bold_circle>
!include <material/arrow_up_bold_circle_outline>
!include <material/arrow_up_bold_hexagon_outline>
!include <material/arrow_up_box>
!include <material/arrow_up_drop_circle>
!include <material/arrow_up_drop_circle_outline>
!include <material/arrow_up_thick>
!include <material/artist>
!include <material/assistant>
!include <material/asterisk>
!include <material/at>
!include <material/atlassian>
!include <material/atom>
!include <material/attachment>
!include <material/audiobook>
!include <material/auto_fix>
!include <material/autorenew>
!include <material/auto_upload>
!include <material/av_timer>
!include <material/azure>
!include <material/baby>
!include <material/baby_buggy>
!include <material/backburger>
!include <material/backspace>
!include <material/backup_restore>
!include <material/bandcamp>
!include <material/bank>
!include <material/barcode>
!include <material/barcode_scan>
!include <material/barley>
!include <material/barrel>
!include <material/basecamp>
!include <material/basket>
!include <material/basketball>
!include <material/basket_fill>
!include <material/basket_unfill>
!include <material/battery>
!include <material/battery_10>
!include <material/battery_20>
!include <material/battery_30>
!include <material/battery_40>
!include <material/battery_50>
!include <material/battery_60>
!include <material/battery_70>
!include <material/battery_80>
!include <material/battery_90>
!include <material/battery_alert>
!include <material/battery_charging>
!include <material/battery_charging_100>
!include <material/battery_charging_20>
!include <material/battery_charging_30>
!include <material/battery_charging_40>
!include <material/battery_charging_60>
!include <material/battery_charging_80>
!include <material/battery_charging_90>
!include <material/battery_charging_wireless>
!include <material/battery_charging_wireless_10>
!include <material/battery_charging_wireless_20>
!include <material/battery_charging_wireless_30>
!include <material/battery_charging_wireless_40>
!include <material/battery_charging_wireless_50>
!include <material/battery_charging_wireless_60>
!include <material/battery_charging_wireless_70>
!include <material/battery_charging_wireless_80>
!include <material/battery_charging_wireless_90>
!include <material/battery_charging_wireless_alert>
!include <material/battery_charging_wireless_outline>
!include <material/battery_minus>
!include <material/battery_negative>
!include <material/battery_outline>
!include <material/battery_plus>
!include <material/battery_positive>
!include <material/battery_standard>
!include <material/battery_unknown>
!include <material/beach>
!include <material/beaker>
!include <material/beam>
!include <material/beats>
!include <material/beer>
!include <material/behance>
!include <material/bell>
!include <material/bell_off>
!include <material/bell_outline>
!include <material/bell_plus>
!include <material/bell_ring>
!include <material/bell_ring_outline>
!include <material/bell_sleep>
!include <material/beta>
!include <material/bible>
!include <material/bike>
!include <material/bing>
!include <material/binoculars>
!include <material/bio>
!include <material/bitbucket>
!include <material/blackberry>
!include <material/black_mesa>
!include <material/blender>
!include <material/blinds>
!include <material/block_helper>
!include <material/blogger>
!include <material/bluetooth>
!include <material/bluetooth_audio>
!include <material/bluetooth_connect>
!include <material/bluetooth_off>
!include <material/bluetooth_settings>
!include <material/bluetooth_transfer>
!include <material/blur>
!include <material/blur_linear>
!include <material/blur_off>
!include <material/blur_radial>
!include <material/bomb>
!include <material/bomb_off>
!include <material/bone>
!include <material/book>
!include <material/bookmark>
!include <material/bookmark_check>
!include <material/bookmark_music>
!include <material/bookmark_outline>
!include <material/bookmark_plus>
!include <material/bookmark_plus_outline>
!include <material/bookmark_remove>
!include <material/book_minus>
!include <material/book_multiple>
!include <material/book_multiple_variant>
!include <material/book_open>
!include <material/book_open_page_variant>
!include <material/book_open_variant>
!include <material/book_plus>
!include <material/book_secure>
!include <material/book_unsecure>
!include <material/book_variant>
!include <material/boombox>
!include <material/bootstrap>
!include <material/border_all>
!include <material/border_bottom>
!include <material/border_color>
!include <material/border_horizontal>
!include <material/border_inside>
!include <material/border_left>
!include <material/border_none>
!include <material/border_outside>
!include <material/border_right>
!include <material/border_style>
!include <material/border_top>
!include <material/border_vertical>
!include <material/bowl>
!include <material/bowling>
!include <material/bow_tie>
!include <material/box>
!include <material/box_cutter>
!include <material/box_download>
!include <material/box_shadow>
!include <material/box_upload>
!include <material/bridge>
!include <material/briefcase>
!include <material/briefcase_check>
!include <material/briefcase_download>
!include <material/briefcase_outline>
!include <material/briefcase_upload>
!include <material/brightness>
!include <material/brightness_1>
!include <material/brightness_2>
!include <material/brightness_3>
!include <material/brightness_4>
!include <material/brightness_5>
!include <material/brightness_6>
!include <material/brightness_7>
!include <material/brightness_auto>
!include <material/broom>
!include <material/brush>
!include <material/buffer>
!include <material/bug>
!include <material/bulletin_board>
!include <material/bullhorn>
!include <material/bullseye>
!include <material/burst_mode>
!include <material/bus>
!include <material/bus_articulated_end>
!include <material/bus_articulated_front>
!include <material/bus_double_decker>
!include <material/bus_school>
!include <material/bus_side>
!include <material/cached>
!include <material/cake>
!include <material/cake_layered>
!include <material/cake_variant>
!include <material/calculator>
!include <material/calculator_off>
!include <material/calendar>
!include <material/calendar_blank>
!include <material/calendar_check>
!include <material/calendar_clock>
!include <material/calendar_multiple>
!include <material/calendar_multiple_check>
!include <material/calendar_plus>
!include <material/calendar_question>
!include <material/calendar_range>
!include <material/calendar_remove>
!include <material/calendar_select>
!include <material/calendar_text>
!include <material/calendar_today>
!include <material/call_made>
!include <material/call_merge>
!include <material/call_missed>
!include <material/call_received>
!include <material/call_split>
!include <material/camcorder>
!include <material/camcorder_box>
!include <material/camcorder_box_off>
!include <material/camcorder_off>
!include <material/camera>
!include <material/camera_burst>
!include <material/camera_enhance>
!include <material/camera_front>
!include <material/camera_front_variant>
!include <material/camera_gopro>
!include <material/camera_iris>
!include <material/camera_metering_center>
!include <material/camera_metering_matrix>
!include <material/camera_metering_partial>
!include <material/camera_metering_spot>
!include <material/camera_off>
!include <material/camera_party_mode>
!include <material/camera_rear>
!include <material/camera_rear_variant>
!include <material/camera_switch>
!include <material/camera_timer>
!include <material/cancel>
!include <material/candle>
!include <material/candycane>
!include <material/cannabis>
!include <material/car>
!include <material/caravan>
!include <material/car_battery>
!include <material/car_connected>
!include <material/car_convertable>
!include <material/cards>
!include <material/cards_outline>
!include <material/cards_playing_outline>
!include <material/cards_variant>
!include <material/car_estate>
!include <material/car_hatchback>
!include <material/car_pickup>
!include <material/carrot>
!include <material/car_side>
!include <material/car_sports>
!include <material/cart>
!include <material/cart_off>
!include <material/cart_outline>
!include <material/cart_plus>
!include <material/car_wash>
!include <material/cash>
!include <material/cash_100>
!include <material/cash_multiple>
!include <material/cash_usd>
!include <material/cast>
!include <material/cast_connected>
!include <material/castle>
!include <material/cast_off>
!include <material/cat>
!include <material/cctv>
!include <material/ceiling_light>
!include <material/cellphone>
!include <material/cellphone_android>
!include <material/cellphone_basic>
!include <material/cellphone_dock>
!include <material/cellphone_iphone>
!include <material/cellphone_link>
!include <material/cellphone_link_off>
!include <material/cellphone_settings>
!include <material/cellphone_wireless>
!include <material/certificate>
!include <material/chair_school>
!include <material/chart_arc>
!include <material/chart_areaspline>
!include <material/chart_bar>
!include <material/chart_bar_stacked>
!include <material/chart_bubble>
!include <material/chart_donut>
!include <material/chart_donut_variant>
!include <material/chart_gantt>
!include <material/chart_histogram>
!include <material/chart_line>
!include <material/chart_line_stacked>
!include <material/chart_line_variant>
!include <material/chart_pie>
!include <material/chart_scatterplot_hexbin>
!include <material/chart_timeline>
!include <material/check>
!include <material/check_all>
!include <material/check_bookmark>
!include <material/checkbox_blank>
!include <material/checkbox_blank_circle>
!include <material/checkbox_blank_circle_outline>
!include <material/checkbox_blank_outline>
!include <material/checkbox_marked>
!include <material/checkbox_marked_circle>
!include <material/checkbox_marked_circle_outline>
!include <material/checkbox_marked_outline>
!include <material/checkbox_multiple_blank>
!include <material/checkbox_multiple_blank_circle>
!include <material/checkbox_multiple_blank_circle_outline>
!include <material/checkbox_multiple_blank_outline>
!include <material/checkbox_multiple_marked>
!include <material/checkbox_multiple_marked_circle>
!include <material/checkbox_multiple_marked_circle_outline>
!include <material/checkbox_multiple_marked_outline>
!include <material/check_circle>
!include <material/check_circle_outline>
!include <material/checkerboard>
!include <material/chemical_weapon>
!include <material/chevron_double_down>
!include <material/chevron_double_left>
!include <material/chevron_double_right>
!include <material/chevron_double_up>
!include <material/chevron_down>
!include <material/chevron_left>
!include <material/chevron_right>
!include <material/chevron_up>
!include <material/chili_hot>
!include <material/chili_medium>
!include <material/chili_mild>
!include <material/chip>
!include <material/church>
!include <material/circle>
!include <material/circle_outline>
!include <material/cisco_webex>
!include <material/city>
!include <material/clapperboard>
!include <material/clipboard>
!include <material/clipboard_account>
!include <material/clipboard_alert>
!include <material/clipboard_arrow_down>
!include <material/clipboard_arrow_left>
!include <material/clipboard_check>
!include <material/clipboard_flow>
!include <material/clipboard_outline>
!include <material/clipboard_plus>
!include <material/clipboard_text>
!include <material/clippy>
!include <material/clock>
!include <material/clock_alert>
!include <material/clock_end>
!include <material/clock_fast>
!include <material/clock_in>
!include <material/clock_out>
!include <material/clock_start>
!include <material/close>
!include <material/close_circle>
!include <material/close_circle_outline>
!include <material/closed_caption>
!include <material/close_network>
!include <material/close_octagon>
!include <material/close_octagon_outline>
!include <material/close_outline>
!include <material/cloud>
!include <material/cloud_braces>
!include <material/cloud_check>
!include <material/cloud_circle>
!include <material/cloud_download>
!include <material/cloud_off_outline>
!include <material/cloud_outline>
!include <material/cloud_print>
!include <material/cloud_print_outline>
!include <material/cloud_sync>
!include <material/cloud_tags>
!include <material/cloud_upload>
!include <material/clover>
!include <material/code_array>
!include <material/code_braces>
!include <material/code_brackets>
!include <material/code_equal>
!include <material/code_greater_than>
!include <material/code_greater_than_or_equal>
!include <material/code_less_than>
!include <material/code_less_than_or_equal>
!include <material/code_not_equal>
!include <material/code_not_equal_variant>
!include <material/code_parentheses>
!include <material/codepen>
!include <material/code_string>
!include <material/code_tags>
!include <material/code_tags_check>
!include <material/coffee>
!include <material/coffee_outline>
!include <material/coffee_to_go>
!include <material/coin>
!include <material/coins>
!include <material/collage>
!include <material/color_helper>
!include <material/comment>
!include <material/comment_account>
!include <material/comment_account_outline>
!include <material/comment_alert>
!include <material/comment_alert_outline>
!include <material/comment_check>
!include <material/comment_check_outline>
!include <material/comment_multiple_outline>
!include <material/comment_outline>
!include <material/comment_plus_outline>
!include <material/comment_processing>
!include <material/comment_processing_outline>
!include <material/comment_question>
!include <material/comment_question_outline>
!include <material/comment_remove>
!include <material/comment_remove_outline>
!include <material/comment_text>
!include <material/comment_text_outline>
!include <material/compare>
!include <material/compass>
!include <material/compass_outline>
!include <material/console>
!include <material/console_line>
!include <material/contact_mail>
!include <material/contacts>
!include <material/content_copy>
!include <material/content_cut>
!include <material/content_duplicate>
!include <material/content_paste>
!include <material/content_save>
!include <material/content_save_all>
!include <material/content_save_outline>
!include <material/content_save_settings>
!include <material/contrast>
!include <material/contrast_box>
!include <material/contrast_circle>
!include <material/controller_xbox>
!include <material/cookie>
!include <material/copyright>
!include <material/corn>
!include <material/counter>
!include <material/cow>
!include <material/creation>
!include <material/credit_card>
!include <material/credit_card_multiple>
!include <material/credit_card_off>
!include <material/credit_card_plus>
!include <material/credit_card_scan>
!include <material/crop>
!include <material/crop_free>
!include <material/crop_landscape>
!include <material/crop_portrait>
!include <material/crop_rotate>
!include <material/crop_square>
!include <material/crosshairs>
!include <material/crosshairs_gps>
!include <material/crown>
!include <material/cube>
!include <material/cube_outline>
!include <material/cube_send>
!include <material/cube_unfolded>
!include <material/cup>
!include <material/cup_off>
!include <material/cup_water>
!include <material/currency_btc>
!include <material/currency_chf>
!include <material/currency_cny>
!include <material/currency_eth>
!include <material/currency_eur>
!include <material/currency_gbp>
!include <material/currency_inr>
!include <material/currency_jpy>
!include <material/currency_krw>
!include <material/currency_ngn>
!include <material/currency_rub>
!include <material/currency_sign>
!include <material/currency_try>
!include <material/currency_twd>
!include <material/currency_usd>
!include <material/currency_usd_off>
!include <material/cursor_default>
!include <material/cursor_default_outline>
!include <material/cursor_move>
!include <material/cursor_pointer>
!include <material/cursor_text>
!include <material/data>
!include <material/database>
!include <material/database_minus>
!include <material/database_plus>
!include <material/debug_step_into>
!include <material/debug_step_out>
!include <material/debug_step_over>
!include <material/decagram>
!include <material/decagram_outline>
!include <material/decimal_decrease>
!include <material/decimal_increase>
!include <material/delete>
!include <material/delete_circle>
!include <material/delete_empty>
!include <material/delete_forever>
!include <material/delete_restore>
!include <material/delete_sweep>
!include <material/delete_variant>
!include <material/delta>
!include <material/deskphone>
!include <material/desktop_classic>
!include <material/desktop_mac>
!include <material/desktop_tower>
!include <material/details>
!include <material/developer_board>
!include <material/deviantart>
!include <material/dialpad>
!include <material/diamond>
!include <material/dice>
!include <material/dice_1>
!include <material/dice_2>
!include <material/dice_3>
!include <material/dice_4>
!include <material/dice_5>
!include <material/dice_6>
!include <material/dice_d10>
!include <material/dice_d20>
!include <material/dice_d4>
!include <material/dice_d6>
!include <material/dice_d8>
!include <material/dice_multiple>
!include <material/dictionary>
!include <material/dip_switch>
!include <material/directions>
!include <material/directions_fork>
!include <material/discord>
!include <material/disk>
!include <material/disk_alert>
!include <material/disqus>
!include <material/disqus_outline>
!include <material/division>
!include <material/division_box>
!include <material/dna>
!include <material/dns>
!include <material/document>
!include <material/dolby>
!include <material/domain>
!include <material/donkey>
!include <material/do_not_disturb>
!include <material/do_not_disturb_off>
!include <material/door>
!include <material/door_closed>
!include <material/door_open>
!include <material/dots_horizontal>
!include <material/dots_horizontal_circle>
!include <material/dots_vertical>
!include <material/dots_vertical_circle>
!include <material/douban>
!include <material/download>
!include <material/download_network>
!include <material/drag>
!include <material/drag_horizontal>
!include <material/drag_vertical>
!include <material/drawing>
!include <material/drawing_box>
!include <material/dribbble>
!include <material/dribbble_box>
!include <material/drone>
!include <material/dropbox>
!include <material/drupal>
!include <material/duck>
!include <material/dumbbell>
!include <material/ear_hearing>
!include <material/earth>
!include <material/earth_box>
!include <material/earth_box_off>
!include <material/earth_off>
!include <material/ebay>
!include <material/edge>
!include <material/eject>
!include <material/elephant>
!include <material/elevation_decline>
!include <material/elevation_rise>
!include <material/elevator>
!include <material/email>
!include <material/email_alert>
!include <material/email_open>
!include <material/email_open_outline>
!include <material/email_outline>
!include <material/email_secure>
!include <material/email_variant>
!include <material/emby>
!include <material/emoticon>
!include <material/emoticon_cool>
!include <material/emoticon_dead>
!include <material/emoticon_devil>
!include <material/emoticon_excited>
!include <material/emoticon_happy>
!include <material/emoticon_neutral>
!include <material/emoticon_poop>
!include <material/emoticon_sad>
!include <material/emoticon_tongue>
!include <material/engine>
!include <material/engine_outline>
!include <material/equal>
!include <material/equal_box>
!include <material/eraser>
!include <material/eraser_variant>
!include <material/escalator>
!include <material/ethernet>
!include <material/ethernet_cable>
!include <material/ethernet_cable_off>
!include <material/etsy>
!include <material/eventbrite>
!include <material/evernote>
!include <material/ev_station>
!include <material/exclamation>
!include <material/exit_to_app>
!include <material/export>
!include <material/eye>
!include <material/eyedropper>
!include <material/eyedropper_variant>
!include <material/eye_off>
!include <material/eye_off_outline>
!include <material/eye_outline>
!include <material/face>
!include <material/facebook>
!include <material/facebook_box>
!include <material/facebook_messenger>
!include <material/face_profile>
!include <material/factory>
!include <material/fan>
!include <material/fan_off>
!include <material/fast_forward>
!include <material/fast_forward_outline>
!include <material/fax>
!include <material/feather>
!include <material/ferry>
!include <material/file>
!include <material/file_account>
!include <material/file_chart>
!include <material/file_check>
!include <material/file_cloud>
!include <material/file_delimited>
!include <material/file_document>
!include <material/file_document_box>
!include <material/file_excel>
!include <material/file_excel_box>
!include <material/file_export>
!include <material/file_find>
!include <material/file_hidden>
!include <material/file_image>
!include <material/file_image_box>
!include <material/file_import>
!include <material/file_lock>
!include <material/file_move>
!include <material/file_multiple>
!include <material/file_music>
!include <material/file_outline>
!include <material/file_pdf>
!include <material/file_pdf_box>
!include <material/file_percent>
!include <material/file_plus>
!include <material/file_powerpoint>
!include <material/file_powerpoint_box>
!include <material/file_presentation_box>
!include <material/file_restore>
!include <material/file_send>
!include <material/file_tree>
!include <material/file_video>
!include <material/file_word>
!include <material/file_word_box>
!include <material/file_xml>
!include <material/fill>
!include <material/film>
!include <material/filmstrip>
!include <material/filmstrip_off>
!include <material/filter>
!include <material/filter_outline>
!include <material/filter_remove>
!include <material/filter_remove_outline>
!include <material/filter_variant>
!include <material/find_replace>
!include <material/fingerprint>
!include <material/fire>
!include <material/fish>
!include <material/flag>
!include <material/flag_checkered>
!include <material/flag_checkered_variant>
!include <material/flag_outline>
!include <material/flag_outline_variant>
!include <material/flag_triangle>
!include <material/flag_variant>
!include <material/flash>
!include <material/flash_auto>
!include <material/flash_circle>
!include <material/flashlight>
!include <material/flashlight_off>
!include <material/flash_off>
!include <material/flash_outline>
!include <material/flash_red_eye>
!include <material/flask>
!include <material/flask_empty>
!include <material/flask_empty_outline>
!include <material/flask_outline>
!include <material/flattr>
!include <material/flickr_after>
!include <material/flickr_before>
!include <material/flip_to_back>
!include <material/flip_to_front>
!include <material/floor_plan>
!include <material/floppy>
!include <material/flower>
!include <material/folder>
!include <material/folder_account>
!include <material/folder_download>
!include <material/folder_google_drive>
!include <material/folder_image>
!include <material/folder_lock>
!include <material/folder_lock_open>
!include <material/folder_move>
!include <material/folder_multiple>
!include <material/folder_multiple_image>
!include <material/folder_multiple_outline>
!include <material/folder_open>
!include <material/folder_outline>
!include <material/folder_outline_lock>
!include <material/folder_plus>
!include <material/folder_remove>
!include <material/folder_star>
!include <material/folder_upload>
!include <material/font_awesome>
!include <material/food>
!include <material/food_apple>
!include <material/food_croissant>
!include <material/food_fork_drink>
!include <material/food_off>
!include <material/food_variant>
!include <material/football>
!include <material/football_australian>
!include <material/football_helmet>
!include <material/footer>
!include <material/forklift>
!include <material/format_align_bottom>
!include <material/format_align_center>
!include <material/format_align_justify>
!include <material/format_align_left>
!include <material/format_align_middle>
!include <material/format_align_right>
!include <material/format_align_top>
!include <material/format_annotation_plus>
!include <material/format_bold>
!include <material/format_clear>
!include <material/format_color>
!include <material/format_color_fill>
!include <material/format_color_text>
!include <material/format_float_center>
!include <material/format_float_left>
!include <material/format_float_none>
!include <material/format_float_right>
!include <material/format_font>
!include <material/format_header_1>
!include <material/format_header_2>
!include <material/format_header_3>
!include <material/format_header_4>
!include <material/format_header_5>
!include <material/format_header_6>
!include <material/format_header_decrease>
!include <material/format_header_down>
!include <material/format_header_equal>
!include <material/format_header_increase>
!include <material/format_header_pound>
!include <material/format_header_up>
!include <material/format_horizontal_align_center>
!include <material/format_horizontal_align_left>
!include <material/format_horizontal_align_right>
!include <material/format_indent_decrease>
!include <material/format_indent_increase>
!include <material/format_italic>
!include <material/format_line_spacing>
!include <material/format_line_style>
!include <material/format_line_weight>
!include <material/format_list_bulleted>
!include <material/format_list_bulleted_type>
!include <material/format_list_checks>
!include <material/format_list_numbers>
!include <material/format_page_break>
!include <material/format_paint>
!include <material/format_paragraph>
!include <material/format_pilcrow>
!include <material/format_quote_close>
!include <material/format_quote_open>
!include <material/format_rotate_90>
!include <material/format_section>
!include <material/format_size>
!include <material/format_strikethrough>
!include <material/format_strikethrough_variant>
!include <material/format_subscript>
!include <material/format_superscript>
!include <material/format_text>
!include <material/format_textdirection_l_to_r>
!include <material/format_textdirection_r_to_l>
!include <material/format_title>
!include <material/format_underline>
!include <material/format_vertical_align_bottom>
!include <material/format_vertical_align_center>
!include <material/format_vertical_align_top>
!include <material/format_wrap_inline>
!include <material/format_wrap_square>
!include <material/format_wrap_tight>
!include <material/format_wrap_top_bottom>
!include <material/forum>
!include <material/forum_outline>
!include <material/forward>
!include <material/foursquare>
!include <material/fridge>
!include <material/fridge_filled>
!include <material/fridge_filled_bottom>
!include <material/fridge_filled_top>
!include <material/fuel>
!include <material/fullscreen>
!include <material/fullscreen_exit>
!include <material/function>
!include <material/gamepad>
!include <material/gamepad_variant>
!include <material/garage>
!include <material/garage_open>
!include <material/gas_cylinder>
!include <material/gas_station>
!include <material/gate>
!include <material/gauge>
!include <material/gavel>
!include <material/gender_female>
!include <material/gender_male>
!include <material/gender_male_female>
!include <material/gender_transgender>
!include <material/gesture>
!include <material/gesture_double_tap>
!include <material/gesture_swipe_down>
!include <material/gesture_swipe_left>
!include <material/gesture_swipe_right>
!include <material/gesture_swipe_up>
!include <material/gesture_tap>
!include <material/gesture_two_double_tap>
!include <material/gesture_two_tap>
!include <material/ghost>
!include <material/gift>
!include <material/git>
!include <material/github_box>
!include <material/github_circle>
!include <material/github_face>
!include <material/glassdoor>
!include <material/glasses>
!include <material/glass_flute>
!include <material/glass_mug>
!include <material/glass_stange>
!include <material/glass_tulip>
!include <material/gmail>
!include <material/gnome>
!include <material/golf>
!include <material/gondola>
!include <material/google>
!include <material/google_analytics>
!include <material/google_assistant>
!include <material/google_cardboard>
!include <material/google_chrome>
!include <material/google_circles>
!include <material/google_circles_communities>
!include <material/google_circles_extended>
!include <material/google_circles_group>
!include <material/google_controller>
!include <material/google_controller_off>
!include <material/google_drive>
!include <material/google_earth>
!include <material/google_glass>
!include <material/google_home>
!include <material/google_keep>
!include <material/google_maps>
!include <material/google_nearby>
!include <material/google_pages>
!include <material/google_photos>
!include <material/google_physical_web>
!include <material/google_play>
!include <material/google_plus>
!include <material/google_plus_box>
!include <material/google_translate>
!include <material/google_wallet>
!include <material/gradient>
!include <material/grease_pencil>
!include <material/grid>
!include <material/grid_large>
!include <material/grid_off>
!include <material/group>
!include <material/guitar_acoustic>
!include <material/guitar_electric>
!include <material/guy_fawkes_mask>
!include <material/hackernews>
!include <material/hamburger>
!include <material/hand_pointing_right>
!include <material/hanger>
!include <material/hangouts>
!include <material/harddisk>
!include <material/headphones>
!include <material/headphones_box>
!include <material/headphones_off>
!include <material/headphones_settings>
!include <material/headset>
!include <material/headset_dock>
!include <material/headset_off>
!include <material/heart>
!include <material/heart_box>
!include <material/heart_box_outline>
!include <material/heart_broken>
!include <material/heart_half>
!include <material/heart_half_full>
!include <material/heart_half_outline>
!include <material/heart_off>
!include <material/heart_outline>
!include <material/heart_pulse>
!include <material/help>
!include <material/help_box>
!include <material/help_circle>
!include <material/help_circle_outline>
!include <material/help_network>
!include <material/hexagon>
!include <material/hexagon_multiple>
!include <material/hexagon_outline>
!include <material/high_definition>
!include <material/highway>
!include <material/history>
!include <material/hololens>
!include <material/home>
!include <material/home_account>
!include <material/home_assistant>
!include <material/home_automation>
!include <material/home_circle>
!include <material/home_heart>
!include <material/home_map_marker>
!include <material/home_modern>
!include <material/home_outline>
!include <material/home_variant>
!include <material/hook>
!include <material/hook_off>
!include <material/hops>
!include <material/hospital>
!include <material/hospital_building>
!include <material/hospital_marker>
!include <material/hotel>
!include <material/hot_tub>
!include <material/houzz_box>
!include <material/hulu>
!include <material/human>
!include <material/human_child>
!include <material/human_female>
!include <material/human_greeting>
!include <material/human_handsdown>
!include <material/human_handsup>
!include <material/human_male>
!include <material/human_male_female>
!include <material/human_pregnant>
!include <material/humble_bundle>
!include <material/ice_cream>
!include <material/image>
!include <material/image_album>
!include <material/image_area>
!include <material/image_area_close>
!include <material/image_broken>
!include <material/image_broken_variant>
!include <material/image_filter>
!include <material/image_filter_black_white>
!include <material/image_filter_center_focus>
!include <material/image_filter_center_focus_weak>
!include <material/image_filter_drama>
!include <material/image_filter_frames>
!include <material/image_filter_hdr>
!include <material/image_filter_none>
!include <material/image_filter_tilt_shift>
!include <material/image_filter_vintage>
!include <material/image_multiple>
!include <material/image_off>
!include <material/import>
!include <material/inbox>
!include <material/inbox_arrow_down>
!include <material/inbox_arrow_up>
!include <material/incognito>
!include <material/indent>
!include <material/infinity>
!include <material/information>
!include <material/information_outline>
!include <material/information_variant>
!include <material/instagram>
!include <material/instapaper>
!include <material/internet_explorer>
!include <material/invert_colors>
!include <material/itunes>
!include <material/jeepney>
!include <material/jira>
!include <material/jsfiddle>
!include <material/json>
!include <material/karate>
!include <material/keg>
!include <material/kettle>
!include <material/key>
!include <material/keyboard>
!include <material/keyboard_backspace>
!include <material/keyboard_caps>
!include <material/keyboard_close>
!include <material/keyboard_off>
!include <material/keyboard_return>
!include <material/keyboard_tab>
!include <material/keyboard_variant>
!include <material/key_change>
!include <material/key_minus>
!include <material/key_plus>
!include <material/key_remove>
!include <material/key_variant>
!include <material/kickstarter>
!include <material/kodi>
!include <material/label>
!include <material/label_outline>
!include <material/ladybug>
!include <material/lambda>
!include <material/lamp>
!include <material/lan>
!include <material/lan_connect>
!include <material/lan_disconnect>
!include <material/language_c>
!include <material/language_cpp>
!include <material/language_csharp>
!include <material/language_css3>
!include <material/language_go>
!include <material/language_html5>
!include <material/language_javascript>
!include <material/language_php>
!include <material/language_python>
!include <material/language_python_text>
!include <material/language_r>
!include <material/language_swift>
!include <material/language_typescript>
!include <material/lan_pending>
!include <material/laptop>
!include <material/laptop_chromebook>
!include <material/laptop_mac>
!include <material/laptop_off>
!include <material/laptop_windows>
!include <material/lastfm>
!include <material/lastpass>
!include <material/launch>
!include <material/lava_lamp>
!include <material/layers>
!include <material/layers_off>
!include <material/lead_pencil>
!include <material/leaf>
!include <material/led_off>
!include <material/led_on>
!include <material/led_outline>
!include <material/led_strip>
!include <material/led_variant_off>
!include <material/led_variant_on>
!include <material/led_variant_outline>
!include <material/library>
!include <material/library_books>
!include <material/library_music>
!include <material/library_plus>
!include <material/lightbulb>
!include <material/lightbulb_on>
!include <material/lightbulb_on_outline>
!include <material/lightbulb_outline>
!include <material/link>
!include <material/linkedin>
!include <material/linkedin_box>
!include <material/link_off>
!include <material/link_variant>
!include <material/link_variant_off>
!include <material/linode>
!include <material/linux>
!include <material/loading>
!include <material/lock>
!include <material/locker>
!include <material/locker_multiple>
!include <material/lock_open>
!include <material/lock_open_outline>
!include <material/lock_outline>
!include <material/lock_pattern>
!include <material/lock_plus>
!include <material/lock_reset>
!include <material/login>
!include <material/login_variant>
!include <material/logout>
!include <material/logout_variant>
!include <material/looks>
!include <material/loop>
!include <material/loupe>
!include <material/lumx>
!include <material/magnet>
!include <material/magnet_on>
!include <material/magnify>
!include <material/magnify_minus>
!include <material/magnify_minus_outline>
!include <material/magnify_plus>
!include <material/magnify_plus_outline>
!include <material/mailbox>
!include <material/mail_ru>
!include <material/map>
!include <material/map_marker>
!include <material/map_marker_circle>
!include <material/map_marker_minus>
!include <material/map_marker_multiple>
!include <material/map_marker_off>
!include <material/map_marker_outline>
!include <material/map_marker_plus>
!include <material/map_marker_radius>
!include <material/margin>
!include <material/markdown>
!include <material/marker>
!include <material/marker_check>
!include <material/martini>
!include <material/material_ui>
!include <material/matrix>
!include <material/maxcdn>
!include <material/medical_bag>
!include <material/medium>
!include <material/memory>
!include <material/menu>
!include <material/menu_down>
!include <material/menu_down_outline>
!include <material/menu_left>
!include <material/menu_right>
!include <material/menu_up>
!include <material/menu_up_outline>
!include <material/message>
!include <material/message_alert>
!include <material/message_bulleted>
!include <material/message_bulleted_off>
!include <material/message_draw>
!include <material/message_image>
!include <material/message_outline>
!include <material/message_plus>
!include <material/message_processing>
!include <material/message_reply>
!include <material/message_reply_text>
!include <material/message_settings>
!include <material/message_settings_variant>
!include <material/message_text>
!include <material/message_text_outline>
!include <material/message_video>
!include <material/meteor>
!include <material/metronome>
!include <material/metronome_tick>
!include <material/microphone>
!include <material/microphone_off>
!include <material/microphone_outline>
!include <material/microphone_settings>
!include <material/microphone_variant>
!include <material/microphone_variant_off>
!include <material/microscope>
!include <material/micro_sd>
!include <material/microsoft>
!include <material/minecraft>
!include <material/minus>
!include <material/minus_box>
!include <material/minus_box_outline>
!include <material/minus_circle>
!include <material/minus_circle_outline>
!include <material/minus_network>
!include <material/mixcloud>
!include <material/mixer>
!include <material/monitor>
!include <material/monitor_multiple>
!include <material/more>
!include <material/mouse>
!include <material/mouse_off>
!include <material/mouse_variant>
!include <material/mouse_variant_off>
!include <material/move_resize>
!include <material/move_resize_variant>
!include <material/movie>
!include <material/movie_roll>
!include <material/multiplication>
!include <material/multiplication_box>
!include <material/mushroom>
!include <material/mushroom_outline>
!include <material/music>
!include <material/music_box>
!include <material/music_box_outline>
!include <material/music_circle>
!include <material/music_note>
!include <material/music_note_bluetooth>
!include <material/music_note_bluetooth_off>
!include <material/music_note_eighth>
!include <material/music_note_half>
!include <material/music_note_off>
!include <material/music_note_quarter>
!include <material/music_note_sixteenth>
!include <material/music_note_whole>
!include <material/music_off>
!include <material/nature>
!include <material/nature_people>
!include <material/navigation>
!include <material/near_me>
!include <material/needle>
!include <material/nest_protect>
!include <material/nest_thermostat>
!include <material/netflix>
!include <material/network>
!include <material/new_box>
!include <material/newspaper>
!include <material/nfc>
!include <material/nfc_tap>
!include <material/nfc_variant>
!include <material/ninja>
!include <material/nintendo_switch>
!include <material/no>
!include <material/nodejs>
!include <material/note>
!include <material/notebook>
!include <material/note_multiple>
!include <material/note_multiple_outline>
!include <material/note_outline>
!include <material/note_plus>
!include <material/note_plus_outline>
!include <material/not_equal>
!include <material/note_text>
!include <material/notification_clear_all>
!include <material/npm>
!include <material/nuke>
!include <material/null>
!include <material/numeric>
!include <material/numeric_0_box>
!include <material/numeric_0_box_multiple_outline>
!include <material/numeric_0_box_outline>
!include <material/numeric_1_box>
!include <material/numeric_1_box_multiple_outline>
!include <material/numeric_1_box_outline>
!include <material/numeric_2_box>
!include <material/numeric_2_box_multiple_outline>
!include <material/numeric_2_box_outline>
!include <material/numeric_3_box>
!include <material/numeric_3_box_multiple_outline>
!include <material/numeric_3_box_outline>
!include <material/numeric_4_box>
!include <material/numeric_4_box_multiple_outline>
!include <material/numeric_4_box_outline>
!include <material/numeric_5_box>
!include <material/numeric_5_box_multiple_outline>
!include <material/numeric_5_box_outline>
!include <material/numeric_6_box>
!include <material/numeric_6_box_multiple_outline>
!include <material/numeric_6_box_outline>
!include <material/numeric_7_box>
!include <material/numeric_7_box_multiple_outline>
!include <material/numeric_7_box_outline>
!include <material/numeric_8_box>
!include <material/numeric_8_box_multiple_outline>
!include <material/numeric_8_box_outline>
!include <material/numeric_9_box>
!include <material/numeric_9_box_multiple_outline>
!include <material/numeric_9_box_outline>
!include <material/numeric_9_plus_box>
!include <material/numeric_9_plus_box_multiple_outline>
!include <material/numeric_9_plus_box_outline>
!include <material/nut>
!include <material/nutrition>
!include <material/oar>
!include <material/octagon>
!include <material/octagon_outline>
!include <material/octagram>
!include <material/octagram_outline>
!include <material/odnoklassniki>
!include <material/office>
!include <material/oil>
!include <material/oil_temperature>
!include <material/omega>
!include <material/onedrive>
!include <material/onenote>
!include <material/opacity>
!include <material/openid>
!include <material/open_in_app>
!include <material/open_in_new>
!include <material/opera>
!include <material/orbit>
!include <material/ornament>
!include <material/ornament_variant>
!include <material/outbox>
!include <material/outdent>
!include <material/owl>
!include <material/package>
!include <material/package_down>
!include <material/package_up>
!include <material/package_variant>
!include <material/package_variant_closed>
!include <material/page_first>
!include <material/page_last>
!include <material/page_layout_body>
!include <material/page_layout_footer>
!include <material/page_layout_header>
!include <material/page_layout_sidebar_left>
!include <material/page_layout_sidebar_right>
!include <material/palette>
!include <material/palette_advanced>
!include <material/panda>
!include <material/pandora>
!include <material/panorama>
!include <material/panorama_fisheye>
!include <material/panorama_horizontal>
!include <material/panorama_vertical>
!include <material/panorama_wide_angle>
!include <material/paperclip>
!include <material/paper_cut_vertical>
!include <material/parking>
!include <material/passport>
!include <material/pause>
!include <material/pause_circle>
!include <material/pause_circle_outline>
!include <material/pause_octagon>
!include <material/pause_octagon_outline>
!include <material/paw>
!include <material/paw_off>
!include <material/pen>
!include <material/pencil>
!include <material/pencil_box>
!include <material/pencil_box_outline>
!include <material/pencil_circle>
!include <material/pencil_circle_outline>
!include <material/pencil_lock>
!include <material/pencil_off>
!include <material/pentagon>
!include <material/pentagon_outline>
!include <material/people>
!include <material/percent>
!include <material/periodic_table_co2>
!include <material/periscope>
!include <material/person_box>
!include <material/person_minus>
!include <material/person_plus>
!include <material/pharmacy>
!include <material/phone>
!include <material/phone_bluetooth>
!include <material/phone_classic>
!include <material/phone_forward>
!include <material/phone_hangup>
!include <material/phone_incoming>
!include <material/phone_in_talk>
!include <material/phone_locked>
!include <material/phone_log>
!include <material/phone_minus>
!include <material/phone_missed>
!include <material/phone_outgoing>
!include <material/phone_paused>
!include <material/phone_plus>
!include <material/phone_return>
!include <material/phone_settings>
!include <material/phone_voip>
!include <material/pi>
!include <material/piano>
!include <material/pi_box>
!include <material/picture>
!include <material/pig>
!include <material/pill>
!include <material/pillar>
!include <material/pin>
!include <material/pine_tree>
!include <material/pine_tree_box>
!include <material/pin_off>
!include <material/pinterest>
!include <material/pinterest_box>
!include <material/pipe>
!include <material/pipe_disconnected>
!include <material/pistol>
!include <material/pizza>
!include <material/plane>
!include <material/plane_shield>
!include <material/play>
!include <material/play_box_outline>
!include <material/play_circle>
!include <material/play_circle_outline>
!include <material/playlist_check>
!include <material/playlist_minus>
!include <material/playlist_play>
!include <material/playlist_plus>
!include <material/playlist_remove>
!include <material/play_pause>
!include <material/play_protected_content>
!include <material/playstation>
!include <material/plex>
!include <material/plus>
!include <material/plus_box>
!include <material/plus_box_outline>
!include <material/plus_circle>
!include <material/plus_circle_multiple_outline>
!include <material/plus_circle_outline>
!include <material/plus_network>
!include <material/plus_one>
!include <material/plus_outline>
!include <material/pocket>
!include <material/pokeball>
!include <material/poker_chip>
!include <material/polaroid>
!include <material/poll>
!include <material/poll_box>
!include <material/polymer>
!include <material/pool>
!include <material/popcorn>
!include <material/pot>
!include <material/pot_mix>
!include <material/pound>
!include <material/pound_box>
!include <material/power>
!include <material/power_plug>
!include <material/power_plug_off>
!include <material/power_settings>
!include <material/power_socket>
!include <material/power_socket_eu>
!include <material/power_socket_uk>
!include <material/power_socket_us>
!include <material/prescription>
!include <material/presentation>
!include <material/presentation_play>
!include <material/printer>
!include <material/printer_3d>
!include <material/printer_alert>
!include <material/printer_settings>
!include <material/priority_high>
!include <material/priority_low>
!include <material/professional_hexagon>
!include <material/projector>
!include <material/projector_screen>
!include <material/publish>
!include <material/pulse>
!include <material/puzzle>
!include <material/qqchat>
!include <material/qrcode>
!include <material/qrcode_scan>
!include <material/quadcopter>
!include <material/quality_high>
!include <material/question_mark_circle>
!include <material/quick_reply>
!include <material/quicktime>
!include <material/rabbit>
!include <material/radar>
!include <material/radiator>
!include <material/radio>
!include <material/radioactive>
!include <material/radiobox_blank>
!include <material/radiobox_marked>
!include <material/radio_handheld>
!include <material/radio_tower>
!include <material/raspberrypi>
!include <material/ray_end>
!include <material/ray_end_arrow>
!include <material/ray_start>
!include <material/ray_start_arrow>
!include <material/ray_start_end>
!include <material/ray_vertex>
!include <material/rdio>
!include <material/react>
!include <material/read>
!include <material/receipt>
!include <material/record>
!include <material/record_rec>
!include <material/recycle>
!include <material/reddit>
!include <material/redo>
!include <material/redo_variant>
!include <material/refresh>
!include <material/relative_scale>
!include <material/reload>
!include <material/remote>
!include <material/rename_box>
!include <material/reorder_horizontal>
!include <material/reorder_vertical>
!include <material/repeat>
!include <material/repeat_off>
!include <material/repeat_once>
!include <material/replay>
!include <material/reply>
!include <material/reply_all>
!include <material/reproduction>
!include <material/resize_bottom_right>
!include <material/responsive>
!include <material/restart>
!include <material/restore>
!include <material/rewind>
!include <material/rewind_outline>
!include <material/rhombus>
!include <material/rhombus_outline>
!include <material/ribbon>
!include <material/rice>
!include <material/ring>
!include <material/road>
!include <material/road_variant>
!include <material/robot>
!include <material/rocket>
!include <material/roomba>
!include <material/rotate_3d>
!include <material/rotate_left>
!include <material/rotate_left_variant>
!include <material/rotate_right>
!include <material/rotate_right_variant>
!include <material/rounded_corner>
!include <material/router_wireless>
!include <material/routes>
!include <material/rowing>
!include <material/rss>
!include <material/rss_box>
!include <material/ruler>
!include <material/run>
!include <material/run_fast>
!include <material/sale>
!include <material/sass>
!include <material/satellite>
!include <material/satellite_variant>
!include <material/saxophone>
!include <material/scale>
!include <material/scale_balance>
!include <material/scale_bathroom>
!include <material/scanner>
!include <material/school>
!include <material/screen_rotation>
!include <material/screen_rotation_lock>
!include <material/screwdriver>
!include <material/script>
!include <material/sd>
!include <material/seal>
!include <material/search_web>
!include <material/seat_flat>
!include <material/seat_flat_angled>
!include <material/seat_individual_suite>
!include <material/seat_legroom_extra>
!include <material/seat_legroom_normal>
!include <material/seat_legroom_reduced>
!include <material/seat_recline_extra>
!include <material/seat_recline_normal>
!include <material/security>
!include <material/security_home>
!include <material/security_network>
!include <material/select>
!include <material/select_all>
!include <material/select_inverse>
!include <material/selection>
!include <material/selection_off>
!include <material/select_off>
!include <material/send>
!include <material/send_secure>
!include <material/serial_port>
!include <material/server>
!include <material/server_minus>
!include <material/server_network>
!include <material/server_network_off>
!include <material/server_off>
!include <material/server_plus>
!include <material/server_remove>
!include <material/server_security>
!include <material/set_all>
!include <material/set_center>
!include <material/set_center_right>
!include <material/set_left>
!include <material/set_left_center>
!include <material/set_left_right>
!include <material/set_none>
!include <material/set_right>
!include <material/settings>
!include <material/settings_box>
!include <material/shape>
!include <material/shape_circle_plus>
!include <material/shape_outline>
!include <material/shape_plus>
!include <material/shape_polygon_plus>
!include <material/shape_rectangle_plus>
!include <material/shape_square_plus>
!include <material/share>
!include <material/share_variant>
!include <material/shield>
!include <material/shield_half_full>
!include <material/shield_outline>
!include <material/ship_wheel>
!include <material/shopping>
!include <material/shopping_music>
!include <material/shovel>
!include <material/shovel_off>
!include <material/shredder>
!include <material/shuffle>
!include <material/shuffle_disabled>
!include <material/shuffle_variant>
!include <material/sigma>
!include <material/sigma_lower>
!include <material/signal>
!include <material/signal_2g>
!include <material/signal_3g>
!include <material/signal_4g>
!include <material/signal_hspa>
!include <material/signal_hspa_plus>
!include <material/signal_off>
!include <material/signal_variant>
!include <material/sign_caution>
!include <material/sign_direction>
!include <material/sign_text>
!include <material/silverware>
!include <material/silverware_fork>
!include <material/silverware_spoon>
!include <material/silverware_variant>
!include <material/sim>
!include <material/sim_alert>
!include <material/sim_off>
!include <material/sitemap>
!include <material/skip_backward>
!include <material/skip_forward>
!include <material/skip_next>
!include <material/skip_next_circle>
!include <material/skip_next_circle_outline>
!include <material/skip_previous>
!include <material/skip_previous_circle>
!include <material/skip_previous_circle_outline>
!include <material/skull>
!include <material/skype>
!include <material/skype_business>
!include <material/slack>
!include <material/sleep>
!include <material/sleep_off>
!include <material/smoking>
!include <material/smoking_off>
!include <material/snapchat>
!include <material/snowflake>
!include <material/snowman>
!include <material/soccer>
!include <material/soccer_field>
!include <material/sofa>
!include <material/solid>
!include <material/sort>
!include <material/sort_alphabetical>
!include <material/sort_ascending>
!include <material/sort_descending>
!include <material/sort_numeric>
!include <material/sort_variant>
!include <material/soundcloud>
!include <material/source_branch>
!include <material/source_commit>
!include <material/source_commit_end>
!include <material/source_commit_end_local>
!include <material/source_commit_local>
!include <material/source_commit_next_local>
!include <material/source_commit_start>
!include <material/source_commit_start_next_local>
!include <material/source_fork>
!include <material/source_merge>
!include <material/source_pull>
!include <material/soy_sauce>
!include <material/speaker>
!include <material/speaker_off>
!include <material/speaker_wireless>
!include <material/speedometer>
!include <material/spellcheck>
!include <material/spotify>
!include <material/spotlight>
!include <material/spotlight_beam>
!include <material/spray>
!include <material/spreadsheet>
!include <material/square>
!include <material/square_inc>
!include <material/square_inc_cash>
!include <material/square_outline>
!include <material/square_root>
!include <material/stackexchange>
!include <material/stackoverflow>
!include <material/stadium>
!include <material/stairs>
!include <material/standard_definition>
!include <material/star>
!include <material/star_circle>
!include <material/star_half>
!include <material/star_of_david>
!include <material/star_off>
!include <material/star_outline>
!include <material/steam>
!include <material/steering>
!include <material/step_backward>
!include <material/step_backward_2>
!include <material/step_forward>
!include <material/step_forward_2>
!include <material/stethoscope>
!include <material/sticker>
!include <material/sticker_emoji>
!include <material/stocking>
!include <material/stop>
!include <material/stop_circle>
!include <material/stop_circle_outline>
!include <material/store>
!include <material/store_24_hour>
!include <material/stove>
!include <material/subdirectory_arrow_left>
!include <material/subdirectory_arrow_right>
!include <material/subway>
!include <material/subway_variant>
!include <material/summit>
!include <material/sunglasses>
!include <material/surround_sound>
!include <material/surround_sound_2_0>
!include <material/surround_sound_3_1>
!include <material/surround_sound_5_1>
!include <material/surround_sound_7_1>
!include <material/svg>
!include <material/swap_horizontal>
!include <material/swap_vertical>
!include <material/swim>
!include <material/switch>
!include <material/sword>
!include <material/sword_cross>
!include <material/sync>
!include <material/sync_alert>
!include <material/sync_off>
!include <material/tab>
!include <material/table>
!include <material/table_column>
!include <material/table_column_plus_after>
!include <material/table_column_plus_before>
!include <material/table_column_remove>
!include <material/table_column_width>
!include <material/table_edit>
!include <material/table_large>
!include <material/table_of_contents>
!include <material/table_row>
!include <material/table_row_height>
!include <material/table_row_plus_after>
!include <material/table_row_plus_before>
!include <material/table_row_remove>
!include <material/table_settings>
!include <material/tablet>
!include <material/tablet_android>
!include <material/tablet_ipad>
!include <material/tab_plus>
!include <material/tab_unselected>
!include <material/taco>
!include <material/tag>
!include <material/tag_faces>
!include <material/tag_heart>
!include <material/tag_multiple>
!include <material/tag_outline>
!include <material/tag_plus>
!include <material/tag_remove>
!include <material/tag_text_outline>
!include <material/target>
!include <material/taxi>
!include <material/teamviewer>
!include <material/telegram>
!include <material/television>
!include <material/television_box>
!include <material/television_classic>
!include <material/television_classic_off>
!include <material/television_guide>
!include <material/television_off>
!include <material/temperature_celsius>
!include <material/temperature_fahrenheit>
!include <material/temperature_kelvin>
!include <material/tennis>
!include <material/tent>
!include <material/terrain>
!include <material/test_tube>
!include <material/textbox>
!include <material/textbox_password>
!include <material/text_shadow>
!include <material/text_to_speech>
!include <material/text_to_speech_off>
!include <material/texture>
!include <material/theater>
!include <material/theme_light_dark>
!include <material/thermometer>
!include <material/thermometer_lines>
!include <material/thought_bubble>
!include <material/thought_bubble_outline>
!include <material/thumb_down>
!include <material/thumb_down_outline>
!include <material/thumbs_up_down>
!include <material/thumb_up>
!include <material/thumb_up_outline>
!include <material/ticket>
!include <material/ticket_account>
!include <material/ticket_confirmation>
!include <material/ticket_percent>
!include <material/tie>
!include <material/tilde>
!include <material/timelapse>
!include <material/timer>
!include <material/timer_10>
!include <material/timer_3>
!include <material/timer_off>
!include <material/timer_sand>
!include <material/timer_sand_empty>
!include <material/timer_sand_full>
!include <material/timetable>
!include <material/toggle_switch>
!include <material/toggle_switch_off>
!include <material/tooltip>
!include <material/tooltip_edit>
!include <material/tooltip_image>
!include <material/tooltip_outline>
!include <material/tooltip_outline_plus>
!include <material/tooltip_text>
!include <material/tooth>
!include <material/tor>
!include <material/tower_beach>
!include <material/tower_fire>
!include <material/towing>
!include <material/trackpad>
!include <material/traffic_light>
!include <material/train>
!include <material/tram>
!include <material/transcribe>
!include <material/transcribe_close>
!include <material/transfer>
!include <material/transit_transfer>
!include <material/translate>
!include <material/trash>
!include <material/treasure_chest>
!include <material/tree>
!include <material/trello>
!include <material/trending_down>
!include <material/trending_neutral>
!include <material/trending_up>
!include <material/triangle>
!include <material/triangle_outline>
!include <material/trophy_outline>
!include <material/trophy_variant_outline>
!include <material/truck>
!include <material/truck_delivery>
!include <material/truck_fast>
!include <material/truck_trailer>
!include <material/tshirt_crew>
!include <material/tshirt_v>
!include <material/tumblr>
!include <material/tumblr_reblog>
!include <material/tune>
!include <material/tune_vertical>
!include <material/twitch>
!include <material/twitter>
!include <material/twitter_box>
!include <material/twitter_circle>
!include <material/twitter_retweet>
!include <material/uber>
!include <material/ubuntu>
!include <material/ultra_high_definition>
!include <material/umbraco>
!include <material/umbrella>
!include <material/umbrella_outline>
!include <material/undo>
!include <material/undo_variant>
!include <material/unfold_less_horizontal>
!include <material/unfold_less_vertical>
!include <material/unfold_more_horizontal>
!include <material/unfold_more_vertical>
!include <material/ungroup>
!include <material/unity>
!include <material/untappd>
!include <material/update>
!include <material/upload>
!include <material/upload_multiple>
!include <material/upload_network>
!include <material/usb>
!include <material/vanish>
!include <material/van_passenger>
!include <material/van_utility>
!include <material/vector_arrange_above>
!include <material/vector_arrange_below>
!include <material/vector_circle>
!include <material/vector_circle_variant>
!include <material/vector_combine>
!include <material/vector_curve>
!include <material/vector_difference>
!include <material/vector_difference_ab>
!include <material/vector_difference_ba>
!include <material/vector_intersection>
!include <material/vector_line>
!include <material/vector_point>
!include <material/vector_polygon>
!include <material/vector_polyline>
!include <material/vector_radius>
!include <material/vector_rectangle>
!include <material/vector_selection>
!include <material/vector_square>
!include <material/vector_triangle>
!include <material/vector_union>
!include <material/venmo>
!include <material/verified>
!include <material/vibrate>
!include <material/video>
!include <material/video_3d>
!include <material/video_4k_box>
!include <material/video_input_antenna>
!include <material/video_input_component>
!include <material/video_input_hdmi>
!include <material/video_input_svideo>
!include <material/video_off>
!include <material/video_switch>
!include <material/view_agenda>
!include <material/view_array>
!include <material/view_carousel>
!include <material/view_column>
!include <material/view_dashboard>
!include <material/view_dashboard_variant>
!include <material/view_day>
!include <material/view_grid>
!include <material/view_headline>
!include <material/view_list>
!include <material/view_module>
!include <material/view_parallel>
!include <material/view_quilt>
!include <material/view_sequential>
!include <material/view_stream>
!include <material/view_week>
!include <material/vimeo>
!include <material/vine>
!include <material/violin>
!include <material/visualstudio>
!include <material/vk>
!include <material/vk_box>
!include <material/vk_circle>
!include <material/vlc>
!include <material/voice>
!include <material/voicemail>
!include <material/volume>
!include <material/volume_high>
!include <material/volume_low>
!include <material/volume_medium>
!include <material/volume_minus>
!include <material/volume_mute>
!include <material/volume_off>
!include <material/volume_plus>
!include <material/vpn>
!include <material/vuejs>
!include <material/walk>
!include <material/wall>
!include <material/wallet>
!include <material/wallet_giftcard>
!include <material/wallet_membership>
!include <material/wallet_travel>
!include <material/wan>
!include <material/washing_machine>
!include <material/watch>
!include <material/watch_export>
!include <material/watch_import>
!include <material/watch_vibrate>
!include <material/water>
!include <material/watermark>
!include <material/water_off>
!include <material/water_percent>
!include <material/water_pump>
!include <material/waves>
!include <material/weather_cloudy>
!include <material/weather_fog>
!include <material/weather_hail>
!include <material/weather_lightning>
!include <material/weather_lightning_rainy>
!include <material/weather_night>
!include <material/weather_partlycloudy>
!include <material/weather_pouring>
!include <material/weather_rainy>
!include <material/weather_snowy>
!include <material/weather_snowy_rainy>
!include <material/weather_sunny>
!include <material/weather_sunset>
!include <material/weather_sunset_down>
!include <material/weather_sunset_up>
!include <material/weather_windy>
!include <material/weather_windy_variant>
!include <material/web>
!include <material/webcam>
!include <material/webhook>
!include <material/webpack>
!include <material/wechat>
!include <material/weight>
!include <material/weight_kilogram>
!include <material/whatsapp>
!include <material/wheelchair_accessibility>
!include <material/white_balance_auto>
!include <material/white_balance_incandescent>
!include <material/white_balance_iridescent>
!include <material/white_balance_sunny>
!include <material/widgets>
!include <material/wifi>
!include <material/wifi_off>
!include <material/wii>
!include <material/wiiu>
!include <material/wikipedia>
!include <material/window_close>
!include <material/window_closed>
!include <material/window_maximize>
!include <material/window_minimize>
!include <material/window_open>
!include <material/window_restore>
!include <material/windows>
!include <material/wordpress>
!include <material/worker>
!include <material/wrench>
!include <material/wunderlist>
!include <material/xamarin>
!include <material/xamarin_outline>
!include <material/xaml>
!include <material/xbox>
!include <material/xbox_controller>
!include <material/xbox_controller_battery_alert>
!include <material/xbox_controller_battery_empty>
!include <material/xbox_controller_battery_full>
!include <material/xbox_controller_battery_low>
!include <material/xbox_controller_battery_medium>
!include <material/xbox_controller_battery_unknown>
!include <material/xbox_controller_off>
!include <material/xda>
!include <material/xing>
!include <material/xing_box>
!include <material/xing_circle>
!include <material/xml>
!include <material/xmpp>
!include <material/yammer>
!include <material/yeast>
!include <material/yelp>
!include <material/yin_yang>
!include <material/youtube>
!include <material/youtube_creator_studio>
!include <material/youtube_gaming>
!include <material/youtube_play>
!include <material/youtube_tv>
!include <material/zip_box>

listsprites
@enduml