@startuml
!include <material/baby>
!include <material/baby_buggy>
!include <material/backburger>
!include <material/backspace>
!include <material/backup_restore>
!include <material/bandcamp>
!include <material/bank>
!include <material/barcode>
!include <material/barcode_scan>
!include <material/barley>
!include <material/barrel>
!include <material/basecamp>
!include <material/basket>
!include <material/basketball>
!include <material/basket_fill>
!include <material/basket_unfill>
!include <material/battery>
!include <material/battery_10>
!include <material/battery_20>
!include <material/battery_30>
!include <material/battery_40>
!include <material/battery_50>
!include <material/battery_60>
!include <material/battery_70>
!include <material/battery_80>
!include <material/battery_90>
!include <material/battery_alert>
!include <material/battery_charging>
!include <material/battery_charging_100>
!include <material/battery_charging_20>
!include <material/battery_charging_30>
!include <material/battery_charging_40>
!include <material/battery_charging_60>
!include <material/battery_charging_80>
!include <material/battery_charging_90>
!include <material/battery_charging_wireless>
!include <material/battery_charging_wireless_10>
!include <material/battery_charging_wireless_20>
!include <material/battery_charging_wireless_30>
!include <material/battery_charging_wireless_40>
!include <material/battery_charging_wireless_50>
!include <material/battery_charging_wireless_60>
!include <material/battery_charging_wireless_70>
!include <material/battery_charging_wireless_80>
!include <material/battery_charging_wireless_90>
!include <material/battery_charging_wireless_alert>
!include <material/battery_charging_wireless_outline>
!include <material/battery_minus>
!include <material/battery_negative>
!include <material/battery_outline>
!include <material/battery_plus>
!include <material/battery_positive>
!include <material/battery_standard>
!include <material/battery_unknown>
!include <material/beach>
!include <material/beaker>
!include <material/beam>
!include <material/beats>
!include <material/beer>
!include <material/behance>
!include <material/bell>
!include <material/bell_off>
!include <material/bell_outline>
!include <material/bell_plus>
!include <material/bell_ring>
!include <material/bell_ring_outline>
!include <material/bell_sleep>
!include <material/beta>
!include <material/bible>
!include <material/bike>
!include <material/bing>
!include <material/binoculars>
!include <material/bio>
!include <material/bitbucket>
!include <material/blackberry>
!include <material/black_mesa>
!include <material/blender>
!include <material/blinds>
!include <material/block_helper>
!include <material/blogger>
!include <material/bluetooth>
!include <material/bluetooth_audio>
!include <material/bluetooth_connect>
!include <material/bluetooth_off>
!include <material/bluetooth_settings>
!include <material/bluetooth_transfer>
!include <material/blur>
!include <material/blur_linear>
!include <material/blur_off>
!include <material/blur_radial>
!include <material/bomb>
!include <material/bomb_off>
!include <material/bone>
!include <material/book>
!include <material/bookmark>
!include <material/bookmark_check>
!include <material/bookmark_music>
!include <material/bookmark_outline>
!include <material/bookmark_plus>
!include <material/bookmark_plus_outline>
!include <material/bookmark_remove>
!include <material/book_minus>
!include <material/book_multiple>
!include <material/book_multiple_variant>
!include <material/book_open>
!include <material/book_open_page_variant>
!include <material/book_open_variant>
!include <material/book_plus>
!include <material/book_secure>
!include <material/book_unsecure>
!include <material/book_variant>
!include <material/boombox>
!include <material/bootstrap>
!include <material/border_all>
!include <material/border_bottom>
!include <material/border_color>
!include <material/border_horizontal>
!include <material/border_inside>
!include <material/border_left>
!include <material/border_none>
!include <material/border_outside>
!include <material/border_right>
!include <material/border_style>
!include <material/border_top>
!include <material/border_vertical>
!include <material/bowl>
!include <material/bowling>
!include <material/bow_tie>
!include <material/box>
!include <material/box_cutter>
!include <material/box_download>
!include <material/box_shadow>
!include <material/box_upload>
!include <material/bridge>
!include <material/briefcase>
!include <material/briefcase_check>
!include <material/briefcase_download>
!include <material/briefcase_outline>
!include <material/briefcase_upload>
!include <material/brightness>
!include <material/brightness_1>
!include <material/brightness_2>
!include <material/brightness_3>
!include <material/brightness_4>
!include <material/brightness_5>
!include <material/brightness_6>
!include <material/brightness_7>
!include <material/brightness_auto>
!include <material/broom>
!include <material/brush>
!include <material/buffer>
!include <material/bug>
!include <material/bulletin_board>
!include <material/bullhorn>
!include <material/bullseye>
!include <material/burst_mode>
!include <material/bus>
!include <material/bus_articulated_end>
!include <material/bus_articulated_front>
!include <material/bus_double_decker>
!include <material/bus_school>
!include <material/bus_side>
listsprites
@enduml