@startuml
!include <material/walk>
!include <material/wall>
!include <material/wallet>
!include <material/wallet_giftcard>
!include <material/wallet_membership>
!include <material/wallet_travel>
!include <material/wan>
!include <material/washing_machine>
!include <material/watch>
!include <material/watch_export>
!include <material/watch_import>
!include <material/watch_vibrate>
!include <material/water>
!include <material/watermark>
!include <material/water_off>
!include <material/water_percent>
!include <material/water_pump>
!include <material/waves>
!include <material/weather_cloudy>
!include <material/weather_fog>
!include <material/weather_hail>
!include <material/weather_lightning>
!include <material/weather_lightning_rainy>
!include <material/weather_night>
!include <material/weather_partlycloudy>
!include <material/weather_pouring>
!include <material/weather_rainy>
!include <material/weather_snowy>
!include <material/weather_snowy_rainy>
!include <material/weather_sunny>
!include <material/weather_sunset>
!include <material/weather_sunset_down>
!include <material/weather_sunset_up>
!include <material/weather_windy>
!include <material/weather_windy_variant>
!include <material/web>
!include <material/webcam>
!include <material/webhook>
!include <material/webpack>
!include <material/wechat>
!include <material/weight>
!include <material/weight_kilogram>
!include <material/whatsapp>
!include <material/wheelchair_accessibility>
!include <material/white_balance_auto>
!include <material/white_balance_incandescent>
!include <material/white_balance_iridescent>
!include <material/white_balance_sunny>
!include <material/widgets>
!include <material/wifi>
!include <material/wifi_off>
!include <material/wii>
!include <material/wiiu>
!include <material/wikipedia>
!include <material/window_close>
!include <material/window_closed>
!include <material/window_maximize>
!include <material/window_minimize>
!include <material/window_open>
!include <material/window_restore>
!include <material/windows>
!include <material/wordpress>
!include <material/worker>
!include <material/wrench>
!include <material/wunderlist>
listsprites
@enduml