@startuml
!include <material/rabbit>
!include <material/radar>
!include <material/radiator>
!include <material/radio>
!include <material/radioactive>
!include <material/radiobox_blank>
!include <material/radiobox_marked>
!include <material/radio_handheld>
!include <material/radio_tower>
!include <material/raspberrypi>
!include <material/ray_end>
!include <material/ray_end_arrow>
!include <material/ray_start>
!include <material/ray_start_arrow>
!include <material/ray_start_end>
!include <material/ray_vertex>
!include <material/rdio>
!include <material/react>
!include <material/read>
!include <material/receipt>
!include <material/record>
!include <material/record_rec>
!include <material/recycle>
!include <material/reddit>
!include <material/redo>
!include <material/redo_variant>
!include <material/refresh>
!include <material/relative_scale>
!include <material/reload>
!include <material/remote>
!include <material/rename_box>
!include <material/reorder_horizontal>
!include <material/reorder_vertical>
!include <material/repeat>
!include <material/repeat_off>
!include <material/repeat_once>
!include <material/replay>
!include <material/reply>
!include <material/reply_all>
!include <material/reproduction>
!include <material/resize_bottom_right>
!include <material/responsive>
!include <material/restart>
!include <material/restore>
!include <material/rewind>
!include <material/rewind_outline>
!include <material/rhombus>
!include <material/rhombus_outline>
!include <material/ribbon>
!include <material/rice>
!include <material/ring>
!include <material/road>
!include <material/road_variant>
!include <material/robot>
!include <material/rocket>
!include <material/roomba>
!include <material/rotate_3d>
!include <material/rotate_left>
!include <material/rotate_left_variant>
!include <material/rotate_right>
!include <material/rotate_right_variant>
!include <material/rounded_corner>
!include <material/router_wireless>
!include <material/routes>
!include <material/rowing>
!include <material/rss>
!include <material/rss_box>
!include <material/ruler>
!include <material/run>
!include <material/run_fast>

listsprites
@enduml