@startuml
!include <material/vanish>
!include <material/van_passenger>
!include <material/van_utility>
!include <material/vector_arrange_above>
!include <material/vector_arrange_below>
!include <material/vector_circle>
!include <material/vector_circle_variant>
!include <material/vector_combine>
!include <material/vector_curve>
!include <material/vector_difference>
!include <material/vector_difference_ab>
!include <material/vector_difference_ba>
!include <material/vector_intersection>
!include <material/vector_line>
!include <material/vector_point>
!include <material/vector_polygon>
!include <material/vector_polyline>
!include <material/vector_radius>
!include <material/vector_rectangle>
!include <material/vector_selection>
!include <material/vector_square>
!include <material/vector_triangle>
!include <material/vector_union>
!include <material/venmo>
!include <material/verified>
!include <material/vibrate>
!include <material/video>
!include <material/video_3d>
!include <material/video_4k_box>
!include <material/video_input_antenna>
!include <material/video_input_component>
!include <material/video_input_hdmi>
!include <material/video_input_svideo>
!include <material/video_off>
!include <material/video_switch>
!include <material/view_agenda>
!include <material/view_array>
!include <material/view_carousel>
!include <material/view_column>
!include <material/view_dashboard>
!include <material/view_dashboard_variant>
!include <material/view_day>
!include <material/view_grid>
!include <material/view_headline>
!include <material/view_list>
!include <material/view_module>
!include <material/view_parallel>
!include <material/view_quilt>
!include <material/view_sequential>
!include <material/view_stream>
!include <material/view_week>
!include <material/vimeo>
!include <material/vine>
!include <material/violin>
!include <material/visualstudio>
!include <material/vk>
!include <material/vk_box>
!include <material/vk_circle>
!include <material/vlc>
!include <material/voice>
!include <material/voicemail>
!include <material/volume>
!include <material/volume_high>
!include <material/volume_low>
!include <material/volume_medium>
!include <material/volume_minus>
!include <material/volume_mute>
!include <material/volume_off>
!include <material/volume_plus>
!include <material/vpn>
!include <material/vuejs>
listsprites
@enduml