@startuml
!include <material/data>
!include <material/database>
!include <material/database_minus>
!include <material/database_plus>
!include <material/debug_step_into>
!include <material/debug_step_out>
!include <material/debug_step_over>
!include <material/decagram>
!include <material/decagram_outline>
!include <material/decimal_decrease>
!include <material/decimal_increase>
!include <material/delete>
!include <material/delete_circle>
!include <material/delete_empty>
!include <material/delete_forever>
!include <material/delete_restore>
!include <material/delete_sweep>
!include <material/delete_variant>
!include <material/delta>
!include <material/deskphone>
!include <material/desktop_classic>
!include <material/desktop_mac>
!include <material/desktop_tower>
!include <material/details>
!include <material/developer_board>
!include <material/deviantart>
!include <material/dialpad>
!include <material/diamond>
!include <material/dice>
!include <material/dice_1>
!include <material/dice_2>
!include <material/dice_3>
!include <material/dice_4>
!include <material/dice_5>
!include <material/dice_6>
!include <material/dice_d10>
!include <material/dice_d20>
!include <material/dice_d4>
!include <material/dice_d6>
!include <material/dice_d8>
!include <material/dice_multiple>
!include <material/dictionary>
!include <material/dip_switch>
!include <material/directions>
!include <material/directions_fork>
!include <material/discord>
!include <material/disk>
!include <material/disk_alert>
!include <material/disqus>
!include <material/disqus_outline>
!include <material/division>
!include <material/division_box>
!include <material/dna>
!include <material/dns>
!include <material/document>
!include <material/dolby>
!include <material/domain>
!include <material/donkey>
!include <material/do_not_disturb>
!include <material/do_not_disturb_off>
!include <material/door>
!include <material/door_closed>
!include <material/door_open>
!include <material/dots_horizontal>
!include <material/dots_horizontal_circle>
!include <material/dots_vertical>
!include <material/dots_vertical_circle>
!include <material/douban>
!include <material/download>
!include <material/download_network>
!include <material/drag>
!include <material/drag_horizontal>
!include <material/drag_vertical>
!include <material/drawing>
!include <material/drawing_box>
!include <material/dribbble>
!include <material/dribbble_box>
!include <material/drone>
!include <material/dropbox>
!include <material/drupal>
!include <material/duck>
!include <material/dumbbell>
listsprites
@enduml