@startuml
!include <material/label>
!include <material/label_outline>
!include <material/ladybug>
!include <material/lambda>
!include <material/lamp>
!include <material/lan>
!include <material/lan_connect>
!include <material/lan_disconnect>
!include <material/language_c>
!include <material/language_cpp>
!include <material/language_csharp>
!include <material/language_css3>
!include <material/language_go>
!include <material/language_html5>
!include <material/language_javascript>
!include <material/language_php>
!include <material/language_python>
!include <material/language_python_text>
!include <material/language_r>
!include <material/language_swift>
!include <material/language_typescript>
!include <material/lan_pending>
!include <material/laptop>
!include <material/laptop_chromebook>
!include <material/laptop_mac>
!include <material/laptop_off>
!include <material/laptop_windows>
!include <material/lastfm>
!include <material/lastpass>
!include <material/launch>
!include <material/lava_lamp>
!include <material/layers>
!include <material/layers_off>
!include <material/lead_pencil>
!include <material/leaf>
!include <material/led_off>
!include <material/led_on>
!include <material/led_outline>
!include <material/led_strip>
!include <material/led_variant_off>
!include <material/led_variant_on>
!include <material/led_variant_outline>
!include <material/library>
!include <material/library_books>
!include <material/library_music>
!include <material/library_plus>
!include <material/lightbulb>
!include <material/lightbulb_on>
!include <material/lightbulb_on_outline>
!include <material/lightbulb_outline>
!include <material/link>
!include <material/linkedin>
!include <material/linkedin_box>
!include <material/link_off>
!include <material/link_variant>
!include <material/link_variant_off>
!include <material/linode>
!include <material/linux>
!include <material/loading>
!include <material/lock>
!include <material/locker>
!include <material/locker_multiple>
!include <material/lock_open>
!include <material/lock_open_outline>
!include <material/lock_outline>
!include <material/lock_pattern>
!include <material/lock_plus>
!include <material/lock_reset>
!include <material/login>
!include <material/login_variant>
!include <material/logout>
!include <material/logout_variant>
!include <material/looks>
!include <material/loop>
!include <material/loupe>
!include <material/lumx>
listsprites
@enduml