@startuml
!include <material/hackernews>
!include <material/hamburger>
!include <material/hand_pointing_right>
!include <material/hanger>
!include <material/hangouts>
!include <material/harddisk>
!include <material/headphones>
!include <material/headphones_box>
!include <material/headphones_off>
!include <material/headphones_settings>
!include <material/headset>
!include <material/headset_dock>
!include <material/headset_off>
!include <material/heart>
!include <material/heart_box>
!include <material/heart_box_outline>
!include <material/heart_broken>
!include <material/heart_half>
!include <material/heart_half_full>
!include <material/heart_half_outline>
!include <material/heart_off>
!include <material/heart_outline>
!include <material/heart_pulse>
!include <material/help>
!include <material/help_box>
!include <material/help_circle>
!include <material/help_circle_outline>
!include <material/help_network>
!include <material/hexagon>
!include <material/hexagon_multiple>
!include <material/hexagon_outline>
!include <material/high_definition>
!include <material/highway>
!include <material/history>
!include <material/hololens>
!include <material/home>
!include <material/home_account>
!include <material/home_assistant>
!include <material/home_automation>
!include <material/home_circle>
!include <material/home_heart>
!include <material/home_map_marker>
!include <material/home_modern>
!include <material/home_outline>
!include <material/home_variant>
!include <material/hook>
!include <material/hook_off>
!include <material/hops>
!include <material/hospital>
!include <material/hospital_building>
!include <material/hospital_marker>
!include <material/hotel>
!include <material/hot_tub>
!include <material/houzz_box>
!include <material/hulu>
!include <material/human>
!include <material/human_child>
!include <material/human_female>
!include <material/human_greeting>
!include <material/human_handsdown>
!include <material/human_handsup>
!include <material/human_male>
!include <material/human_male_female>
!include <material/human_pregnant>
!include <material/humble_bundle>
listsprites
@enduml