@startuml
!include <material/magnet>
!include <material/magnet_on>
!include <material/magnify>
!include <material/magnify_minus>
!include <material/magnify_minus_outline>
!include <material/magnify_plus>
!include <material/magnify_plus_outline>
!include <material/mailbox>
!include <material/mail_ru>
!include <material/map>
!include <material/map_marker>
!include <material/map_marker_circle>
!include <material/map_marker_minus>
!include <material/map_marker_multiple>
!include <material/map_marker_off>
!include <material/map_marker_outline>
!include <material/map_marker_plus>
!include <material/map_marker_radius>
!include <material/margin>
!include <material/markdown>
!include <material/marker>
!include <material/marker_check>
!include <material/martini>
!include <material/material_ui>
!include <material/matrix>
!include <material/maxcdn>
!include <material/medical_bag>
!include <material/medium>
!include <material/memory>
!include <material/menu>
!include <material/menu_down>
!include <material/menu_down_outline>
!include <material/menu_left>
!include <material/menu_right>
!include <material/menu_up>
!include <material/menu_up_outline>
!include <material/message>
!include <material/message_alert>
!include <material/message_bulleted>
!include <material/message_bulleted_off>
!include <material/message_draw>
!include <material/message_image>
!include <material/message_outline>
!include <material/message_plus>
!include <material/message_processing>
!include <material/message_reply>
!include <material/message_reply_text>
!include <material/message_settings>
!include <material/message_settings_variant>
!include <material/message_text>
!include <material/message_text_outline>
!include <material/message_video>
!include <material/meteor>
!include <material/metronome>
!include <material/metronome_tick>
!include <material/microphone>
!include <material/microphone_off>
!include <material/microphone_outline>
!include <material/microphone_settings>
!include <material/microphone_variant>
!include <material/microphone_variant_off>
!include <material/microscope>
!include <material/micro_sd>
!include <material/microsoft>
!include <material/minecraft>
!include <material/minus>
!include <material/minus_box>
!include <material/minus_box_outline>
!include <material/minus_circle>
!include <material/minus_circle_outline>
!include <material/minus_network>
!include <material/mixcloud>
!include <material/mixer>
!include <material/monitor>
!include <material/monitor_multiple>
!include <material/more>
!include <material/mouse>
!include <material/mouse_off>
!include <material/mouse_variant>
!include <material/mouse_variant_off>
!include <material/move_resize>
!include <material/move_resize_variant>
!include <material/movie>
!include <material/movie_roll>
!include <material/multiplication>
!include <material/multiplication_box>
!include <material/mushroom>
!include <material/mushroom_outline>
!include <material/music>
!include <material/music_box>
!include <material/music_box_outline>
!include <material/music_circle>
!include <material/music_note>
!include <material/music_note_bluetooth>
!include <material/music_note_bluetooth_off>
!include <material/music_note_eighth>
!include <material/music_note_half>
!include <material/music_note_off>
!include <material/music_note_quarter>
!include <material/music_note_sixteenth>
!include <material/music_note_whole>
!include <material/music_off>
listsprites
@enduml