@startuml
!include <material/package>
!include <material/package_down>
!include <material/package_up>
!include <material/package_variant>
!include <material/package_variant_closed>
!include <material/page_first>
!include <material/page_last>
!include <material/page_layout_body>
!include <material/page_layout_footer>
!include <material/page_layout_header>
!include <material/page_layout_sidebar_left>
!include <material/page_layout_sidebar_right>
!include <material/palette>
!include <material/palette_advanced>
!include <material/panda>
!include <material/pandora>
!include <material/panorama>
!include <material/panorama_fisheye>
!include <material/panorama_horizontal>
!include <material/panorama_vertical>
!include <material/panorama_wide_angle>
!include <material/paperclip>
!include <material/paper_cut_vertical>
!include <material/parking>
!include <material/passport>
!include <material/pause>
!include <material/pause_circle>
!include <material/pause_circle_outline>
!include <material/pause_octagon>
!include <material/pause_octagon_outline>
!include <material/paw>
!include <material/paw_off>
!include <material/pen>
!include <material/pencil>
!include <material/pencil_box>
!include <material/pencil_box_outline>
!include <material/pencil_circle>
!include <material/pencil_circle_outline>
!include <material/pencil_lock>
!include <material/pencil_off>
!include <material/pentagon>
!include <material/pentagon_outline>
!include <material/people>
!include <material/percent>
!include <material/periodic_table_co2>
!include <material/periscope>
!include <material/person_box>
!include <material/person_minus>
!include <material/person_plus>
!include <material/pharmacy>
!include <material/phone>
!include <material/phone_bluetooth>
!include <material/phone_classic>
!include <material/phone_forward>
!include <material/phone_hangup>
!include <material/phone_incoming>
!include <material/phone_in_talk>
!include <material/phone_locked>
!include <material/phone_log>
!include <material/phone_minus>
!include <material/phone_missed>
!include <material/phone_outgoing>
!include <material/phone_paused>
!include <material/phone_plus>
!include <material/phone_return>
!include <material/phone_settings>
!include <material/phone_voip>
!include <material/pi>
!include <material/piano>
!include <material/pi_box>
!include <material/picture>
!include <material/pig>
!include <material/pill>
!include <material/pillar>
!include <material/pin>
!include <material/pine_tree>
!include <material/pine_tree_box>
!include <material/pin_off>
!include <material/pinterest>
!include <material/pinterest_box>
!include <material/pipe>
!include <material/pipe_disconnected>
!include <material/pistol>
!include <material/pizza>
!include <material/plane>
!include <material/plane_shield>
!include <material/play>
!include <material/play_box_outline>
!include <material/play_circle>
!include <material/play_circle_outline>
!include <material/playlist_check>
!include <material/playlist_minus>
!include <material/playlist_play>
!include <material/playlist_plus>
!include <material/playlist_remove>
!include <material/play_pause>
!include <material/play_protected_content>
!include <material/playstation>
!include <material/plex>
!include <material/plus>
!include <material/plus_box>
!include <material/plus_box_outline>
!include <material/plus_circle>
!include <material/plus_circle_multiple_outline>
!include <material/plus_circle_outline>
!include <material/plus_network>
!include <material/plus_one>
!include <material/plus_outline>
!include <material/pocket>
!include <material/pokeball>
!include <material/poker_chip>
!include <material/polaroid>
!include <material/poll>
!include <material/poll_box>
!include <material/polymer>
!include <material/pool>
!include <material/popcorn>
!include <material/pot>
!include <material/pot_mix>
!include <material/pound>
!include <material/pound_box>
!include <material/power>
!include <material/power_plug>
!include <material/power_plug_off>
!include <material/power_settings>
!include <material/power_socket>
!include <material/power_socket_eu>
!include <material/power_socket_uk>
!include <material/power_socket_us>
!include <material/prescription>
!include <material/presentation>
!include <material/presentation_play>
!include <material/printer>
!include <material/printer_3d>
!include <material/printer_alert>
!include <material/printer_settings>
!include <material/priority_high>
!include <material/priority_low>
!include <material/professional_hexagon>
!include <material/projector>
!include <material/projector_screen>
!include <material/publish>
!include <material/pulse>
!include <material/puzzle>
listsprites
@enduml