@startuml
!include <material/gamepad>
!include <material/gamepad_variant>
!include <material/garage>
!include <material/garage_open>
!include <material/gas_cylinder>
!include <material/gas_station>
!include <material/gate>
!include <material/gauge>
!include <material/gavel>
!include <material/gender_female>
!include <material/gender_male>
!include <material/gender_male_female>
!include <material/gender_transgender>
!include <material/gesture>
!include <material/gesture_double_tap>
!include <material/gesture_swipe_down>
!include <material/gesture_swipe_left>
!include <material/gesture_swipe_right>
!include <material/gesture_swipe_up>
!include <material/gesture_tap>
!include <material/gesture_two_double_tap>
!include <material/gesture_two_tap>
!include <material/ghost>
!include <material/gift>
!include <material/git>
!include <material/github_box>
!include <material/github_circle>
!include <material/github_face>
!include <material/glassdoor>
!include <material/glasses>
!include <material/glass_flute>
!include <material/glass_mug>
!include <material/glass_stange>
!include <material/glass_tulip>
!include <material/gmail>
!include <material/gnome>
!include <material/golf>
!include <material/gondola>
!include <material/google>
!include <material/google_analytics>
!include <material/google_assistant>
!include <material/google_cardboard>
!include <material/google_chrome>
!include <material/google_circles>
!include <material/google_circles_communities>
!include <material/google_circles_extended>
!include <material/google_circles_group>
!include <material/google_controller>
!include <material/google_controller_off>
!include <material/google_drive>
!include <material/google_earth>
!include <material/google_glass>
!include <material/google_home>
!include <material/google_keep>
!include <material/google_maps>
!include <material/google_nearby>
!include <material/google_pages>
!include <material/google_photos>
!include <material/google_physical_web>
!include <material/google_play>
!include <material/google_plus>
!include <material/google_plus_box>
!include <material/google_translate>
!include <material/google_wallet>
!include <material/gradient>
!include <material/grease_pencil>
!include <material/grid>
!include <material/grid_large>
!include <material/grid_off>
!include <material/group>
!include <material/guitar_acoustic>
!include <material/guitar_electric>
!include <material/guy_fawkes_mask>

listsprites
@enduml