@startuml
!include <material/ear_hearing>
!include <material/earth>
!include <material/earth_box>
!include <material/earth_box_off>
!include <material/earth_off>
!include <material/ebay>
!include <material/edge>
!include <material/eject>
!include <material/elephant>
!include <material/elevation_decline>
!include <material/elevation_rise>
!include <material/elevator>
!include <material/email>
!include <material/email_alert>
!include <material/email_open>
!include <material/email_open_outline>
!include <material/email_outline>
!include <material/email_secure>
!include <material/email_variant>
!include <material/emby>
!include <material/emoticon>
!include <material/emoticon_cool>
!include <material/emoticon_dead>
!include <material/emoticon_devil>
!include <material/emoticon_excited>
!include <material/emoticon_happy>
!include <material/emoticon_neutral>
!include <material/emoticon_poop>
!include <material/emoticon_sad>
!include <material/emoticon_tongue>
!include <material/engine>
!include <material/engine_outline>
!include <material/equal>
!include <material/equal_box>
!include <material/eraser>
!include <material/eraser_variant>
!include <material/escalator>
!include <material/ethernet>
!include <material/ethernet_cable>
!include <material/ethernet_cable_off>
!include <material/etsy>
!include <material/eventbrite>
!include <material/evernote>
!include <material/ev_station>
!include <material/exclamation>
!include <material/exit_to_app>
!include <material/export>
!include <material/eye>
!include <material/eyedropper>
!include <material/eyedropper_variant>
!include <material/eye_off>
!include <material/eye_off_outline>
!include <material/eye_outline>
listsprites
@enduml