@startuml
!include <material/tab>
!include <material/table>
!include <material/table_column>
!include <material/table_column_plus_after>
!include <material/table_column_plus_before>
!include <material/table_column_remove>
!include <material/table_column_width>
!include <material/table_edit>
!include <material/table_large>
!include <material/table_of_contents>
!include <material/table_row>
!include <material/table_row_height>
!include <material/table_row_plus_after>
!include <material/table_row_plus_before>
!include <material/table_row_remove>
!include <material/table_settings>
!include <material/tablet>
!include <material/tablet_android>
!include <material/tablet_ipad>
!include <material/tab_plus>
!include <material/tab_unselected>
!include <material/taco>
!include <material/tag>
!include <material/tag_faces>
!include <material/tag_heart>
!include <material/tag_multiple>
!include <material/tag_outline>
!include <material/tag_plus>
!include <material/tag_remove>
!include <material/tag_text_outline>
!include <material/target>
!include <material/taxi>
!include <material/teamviewer>
!include <material/telegram>
!include <material/television>
!include <material/television_box>
!include <material/television_classic>
!include <material/television_classic_off>
!include <material/television_guide>
!include <material/television_off>
!include <material/temperature_celsius>
!include <material/temperature_fahrenheit>
!include <material/temperature_kelvin>
!include <material/tennis>
!include <material/tent>
!include <material/terrain>
!include <material/test_tube>
!include <material/textbox>
!include <material/textbox_password>
!include <material/text_shadow>
!include <material/text_to_speech>
!include <material/text_to_speech_off>
!include <material/texture>
!include <material/theater>
!include <material/theme_light_dark>
!include <material/thermometer>
!include <material/thermometer_lines>
!include <material/thought_bubble>
!include <material/thought_bubble_outline>
!include <material/thumb_down>
!include <material/thumb_down_outline>
!include <material/thumbs_up_down>
!include <material/thumb_up>
!include <material/thumb_up_outline>
!include <material/ticket>
!include <material/ticket_account>
!include <material/ticket_confirmation>
!include <material/ticket_percent>
!include <material/tie>
!include <material/tilde>
!include <material/timelapse>
!include <material/timer>
!include <material/timer_10>
!include <material/timer_3>
!include <material/timer_off>
!include <material/timer_sand>
!include <material/timer_sand_empty>
!include <material/timer_sand_full>
!include <material/timetable>
!include <material/toggle_switch>
!include <material/toggle_switch_off>
!include <material/tooltip>
!include <material/tooltip_edit>
!include <material/tooltip_image>
!include <material/tooltip_outline>
!include <material/tooltip_outline_plus>
!include <material/tooltip_text>
!include <material/tooth>
!include <material/tor>
!include <material/tower_beach>
!include <material/tower_fire>
!include <material/towing>
!include <material/trackpad>
!include <material/traffic_light>
!include <material/train>
!include <material/tram>
!include <material/transcribe>
!include <material/transcribe_close>
!include <material/transfer>
!include <material/transit_transfer>
!include <material/translate>
!include <material/trash>
!include <material/treasure_chest>
!include <material/tree>
!include <material/trello>
!include <material/trending_down>
!include <material/trending_neutral>
!include <material/trending_up>
!include <material/triangle>
!include <material/triangle_outline>
!include <material/trophy_outline>
!include <material/trophy_variant_outline>
!include <material/truck>
!include <material/truck_delivery>
!include <material/truck_fast>
!include <material/truck_trailer>
!include <material/tshirt_crew>
!include <material/tshirt_v>
!include <material/tumblr>
!include <material/tumblr_reblog>
!include <material/tune>
!include <material/tune_vertical>
!include <material/twitch>
!include <material/twitter>
!include <material/twitter_box>
!include <material/twitter_circle>
!include <material/twitter_retweet>

listsprites
@enduml